-- Retour arrière : remet logic='none' sur les 40 meubles wired touchés le 2026-07-24
UPDATE furniture_definitions SET logic='none' WHERE id=4490563;  -- wf_act_set_altitude
UPDATE furniture_definitions SET logic='none' WHERE id=4490565;  -- wf_trg_stuff_state
UPDATE furniture_definitions SET logic='none' WHERE id=4490566;  -- wf_trg_user_performs_action
UPDATE furniture_definitions SET logic='none' WHERE id=28408418;  -- wf_var_quest
UPDATE furniture_definitions SET logic='none' WHERE id=28408419;  -- wf_var_quest_chain
UPDATE furniture_definitions SET logic='none' WHERE id=32013615;  -- wf_act_give_var
UPDATE furniture_definitions SET logic='none' WHERE id=32013622;  -- wf_act_remove_var
UPDATE furniture_definitions SET logic='none' WHERE id=32013631;  -- wf_cnd_not_user_performs_action
UPDATE furniture_definitions SET logic='none' WHERE id=32013632;  -- wf_cnd_slc_quantity
UPDATE furniture_definitions SET logic='none' WHERE id=32013633;  -- wf_cnd_team_has_rank
UPDATE furniture_definitions SET logic='none' WHERE id=32013634;  -- wf_cnd_team_has_score
UPDATE furniture_definitions SET logic='none' WHERE id=32013636;  -- wf_cnd_user_performs_action
UPDATE furniture_definitions SET logic='none' WHERE id=32013641;  -- wf_trg_var_changed
UPDATE furniture_definitions SET logic='none' WHERE id=238800259;  -- wf_slc_users_handitem
UPDATE furniture_definitions SET logic='none' WHERE id=246616967;  -- wf_slc_users_bytype
UPDATE furniture_definitions SET logic='none' WHERE id=252293444;  -- wf_slc_furni_altitude
UPDATE furniture_definitions SET logic='none' WHERE id=333117657;  -- wf_slc_furni_onfurni
UPDATE furniture_definitions SET logic='none' WHERE id=352976345;  -- wf_slc_users_onfurni
UPDATE furniture_definitions SET logic='none' WHERE id=373654393;  -- wf_slc_users_with_var
UPDATE furniture_definitions SET logic='none' WHERE id=422001511;  -- wf_slc_furni_signal
UPDATE furniture_definitions SET logic='none' WHERE id=446313468;  -- wf_slc_furni_bytype
UPDATE furniture_definitions SET logic='none' WHERE id=451817134;  -- wf_slc_users_signal
UPDATE furniture_definitions SET logic='none' WHERE id=674941925;  -- wf_slc_furni_with_var
UPDATE furniture_definitions SET logic='none' WHERE id=717724789;  -- wf_slc_furni_picks
UPDATE furniture_definitions SET logic='none' WHERE id=735519086;  -- wf_slc_users_area
UPDATE furniture_definitions SET logic='none' WHERE id=751055284;  -- wf_slc_users_team
UPDATE furniture_definitions SET logic='none' WHERE id=756632562;  -- wf_slc_users_neighborhood
UPDATE furniture_definitions SET logic='none' WHERE id=807283715;  -- wf_slc_users_byname
UPDATE furniture_definitions SET logic='none' WHERE id=857043807;  -- wf_slc_furni_neighborhood
UPDATE furniture_definitions SET logic='none' WHERE id=880755949;  -- wf_slc_users_group
UPDATE furniture_definitions SET logic='none' WHERE id=966610621;  -- wf_slc_furni_area
UPDATE furniture_definitions SET logic='none' WHERE id=987510308;  -- wf_slc_users_byaction
UPDATE furniture_definitions SET logic='none' WHERE id=2000028767;  -- wf_xtra_filter_furni
UPDATE furniture_definitions SET logic='none' WHERE id=2000028784;  -- wf_var_user
UPDATE furniture_definitions SET logic='none' WHERE id=2000028785;  -- wf_var_context
UPDATE furniture_definitions SET logic='none' WHERE id=2000028787;  -- wf_var_furni
UPDATE furniture_definitions SET logic='none' WHERE id=2000028788;  -- wf_slc_remote
UPDATE furniture_definitions SET logic='none' WHERE id=2000028790;  -- wf_var_room
UPDATE furniture_definitions SET logic='none' WHERE id=2000029123;  -- wf_var_reference
UPDATE furniture_definitions SET logic='none' WHERE id=2000029125;  -- wf_trg_recv_signal
