// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Vortex.Database.Context;

#nullable disable

namespace Vortex.Database.Migrations
{
    [DbContext(typeof(VortexDbContext))]
    [Migration("20260628000000_AddFurnitureDefinitionStuffDataType")]
    partial class AddFurnitureDefinitionStuffDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}