-- Triage des wired : chaque boîte sur la page Habbo ou Customs de sa famille.
-- Règle : « Habbo » = boîte que le client officiel sait configurer (elle a un code officiel,
-- reconnu par le serveur) ; « Customs » = ajout de l'hôtel, sans dialogue officiel.
-- Additif et idempotent : ne supprime rien, ne cache rien. Déplace les offres wired qui sont
-- déjà dans la section wired, et crée celles qui manquent.

CREATE TEMPORARY TABLE wired_tri (class_name VARCHAR(200) PRIMARY KEY, famille VARCHAR(20), bucket VARCHAR(40));
INSERT INTO wired_tri (class_name, famille, bucket) VALUES
  ('wf_trg_at_given_time','triggers','habbo'),
  ('wf_trg_at_time_long','triggers','habbo'),
  ('wf_trg_bot_reached_avtr','triggers','habbo'),
  ('wf_trg_bot_reached_stf','triggers','habbo'),
  ('wf_trg_click_furni','triggers','habbo'),
  ('wf_trg_click_tile','triggers','habbo'),
  ('wf_trg_click_user','triggers','habbo'),
  ('wf_trg_clock_counter','triggers','habbo'),
  ('wf_trg_collision','triggers','habbo'),
  ('wf_trg_enter_room','triggers','habbo'),
  ('wf_trg_game_ends','triggers','habbo'),
  ('wf_trg_game_starts','triggers','habbo'),
  ('wf_trg_leave_room','triggers','habbo'),
  ('wf_trg_period_long','triggers','habbo'),
  ('wf_trg_period_short','triggers','habbo'),
  ('wf_trg_periodically','triggers','habbo'),
  ('wf_trg_recv_signal','triggers','habbo'),
  ('wf_trg_says_something','triggers','habbo'),
  ('wf_trg_score_achieved','triggers','habbo'),
  ('wf_trg_state_changed','triggers','habbo'),
  ('wf_trg_stuff_state','triggers','habbo'),
  ('wf_trg_user_performs_action','triggers','habbo'),
  ('wf_trg_var_changed','triggers','habbo'),
  ('wf_trg_walks_off_furni','triggers','habbo'),
  ('wf_trg_walks_on_furni','triggers','habbo'),
  ('wf_trg_afkkkdormeur','triggers','custom_trigger'),
  ('wf_trg_cls_user1','triggers','custom_trigger'),
  ('wf_trg_cls_user2','triggers','custom_trigger'),
  ('wf_trg_cnd_collision','triggers','custom_trigger'),
  ('wf_trg_dice_stop_rolling','triggers','custom_trigger'),
  ('wf_trg_exact_keyword','triggers','custom_trigger'),
  ('wf_trg_idles','triggers','custom_trigger'),
  ('wf_trg_keyboard','triggers','custom_trigger'),
  ('wf_trg_player_click','triggers','custom_trigger'),
  ('wf_trg_player_clicked','triggers','custom_trigger'),
  ('wf_trg_remote_command','triggers','custom_trigger'),
  ('wf_trg_says_cmd','triggers','custom_trigger'),
  ('wf_trg_says_command','triggers','custom_trigger'),
  ('wf_trg_says_sycommand','triggers','custom_trigger'),
  ('wf_trg_starts_dancing','triggers','custom_trigger'),
  ('wf_trg_state_changdd','triggers','custom_trigger'),
  ('wf_trg_stops_dancing','triggers','custom_trigger'),
  ('wf_trg_transaction_complete','triggers','custom_trigger'),
  ('wf_trg_transaction_fail','triggers','custom_trigger'),
  ('wf_trg_unidles','triggers','custom_trigger'),
  ('wf_trg_user_collides_bot','triggers','custom_trigger'),
  ('wf_trg_user_gets_handitem','triggers','custom_trigger'),
  ('wf_act_adjust_clock','effects','habbo'),
  ('wf_act_bot_clothes','effects','habbo'),
  ('wf_act_bot_follow_avatar','effects','habbo'),
  ('wf_act_bot_give_handitem','effects','habbo'),
  ('wf_act_bot_move','effects','habbo'),
  ('wf_act_bot_talk','effects','habbo'),
  ('wf_act_bot_talk_to_avatar','effects','habbo'),
  ('wf_act_bot_teleport','effects','habbo'),
  ('wf_act_call_stacks','effects','habbo'),
  ('wf_act_cancel_transaction','effects','habbo'),
  ('wf_act_change_var_val','effects','habbo'),
  ('wf_act_chase','effects','habbo'),
  ('wf_act_cnd_furni_to_furni','effects','habbo'),
  ('wf_act_control_clock','effects','habbo'),
  ('wf_act_flee','effects','habbo'),
  ('wf_act_forward_user','effects','habbo'),
  ('wf_act_furni_to_user','effects','habbo'),
  ('wf_act_give_effect','effects','habbo'),
  ('wf_act_give_reward','effects','habbo'),
  ('wf_act_give_score','effects','habbo'),
  ('wf_act_give_score_tm','effects','habbo'),
  ('wf_act_give_var','effects','habbo'),
  ('wf_act_join_team','effects','habbo'),
  ('wf_act_kick_user','effects','habbo'),
  ('wf_act_leave_team','effects','habbo'),
  ('wf_act_lower_furni','effects','habbo'),
  ('wf_act_move_furni_to','effects','habbo'),
  ('wf_act_move_rotate','effects','habbo'),
  ('wf_act_move_to_dir','effects','habbo'),
  ('wf_act_mute_triggerer','effects','habbo'),
  ('wf_act_neg_call_stacks','effects','habbo'),
  ('wf_act_neg_send_signal','effects','habbo'),
  ('wf_act_raise_furni','effects','habbo'),
  ('wf_act_rel_mov','effects','habbo'),
  ('wf_act_remove_var','effects','habbo'),
  ('wf_act_reset_timers','effects','habbo'),
  ('wf_act_send_signal','effects','habbo'),
  ('wf_act_set_altitude','effects','habbo'),
  ('wf_act_show_message','effects','habbo'),
  ('wf_act_show_message_room','effects','habbo'),
  ('wf_act_teleport_to','effects','habbo'),
  ('wf_act_teleport_to_room','effects','habbo'),
  ('wf_act_toggle_state','effects','habbo'),
  ('wf_act_toggle_to_rnd','effects','habbo'),
  ('wf_act_add_tag','effects','custom_effect'),
  ('wf_act_all_users_leave_team','effects','custom_effect'),
  ('wf_act_allign_furni_stack','effects','custom_effect'),
  ('wf_act_arith_operation_tag','effects','custom_effect'),
  ('wf_act_close_dice_cstm','effects','custom_effect'),
  ('wf_act_closes_dices','effects','custom_effect'),
  ('wf_act_cnd_toggle_state','effects','custom_effect'),
  ('wf_act_collide_upper','effects','custom_effect'),
  ('wf_act_cond_stacks','effects','custom_effect'),
  ('wf_act_deux_message','effects','custom_effect'),
  ('wf_act_dice_manager','effects','custom_effect'),
  ('wf_act_dont_chase','effects','custom_effect'),
  ('wf_act_dont_chase_top','effects','custom_effect'),
  ('wf_act_double_click','effects','custom_effect'),
  ('wf_act_endgame_team','effects','custom_effect'),
  ('wf_act_execute_for_furni','effects','custom_effect'),
  ('wf_act_execute_for_users','effects','custom_effect'),
  ('wf_act_execute_stack_custom','effects','custom_effect'),
  ('wf_act_execute_stack_one','effects','custom_effect'),
  ('wf_act_freeze','effects','custom_effect'),
  ('wf_act_freeze_habbo','effects','custom_effect'),
  ('wf_act_furni_color','effects','custom_effect'),
  ('wf_act_gamemode_off','effects','custom_effect'),
  ('wf_act_give_achievement','effects','custom_effect'),
  ('wf_act_give_badge','effects','custom_effect'),
  ('wf_act_give_credits','effects','custom_effect'),
  ('wf_act_give_currency','effects','custom_effect'),
  ('wf_act_give_diamonds','effects','custom_effect'),
  ('wf_act_give_duckets','effects','custom_effect'),
  ('wf_act_give_enable','effects','custom_effect'),
  ('wf_act_give_furni','effects','custom_effect'),
  ('wf_act_give_handitem','effects','custom_effect'),
  ('wf_act_give_pointss','effects','custom_effect'),
  ('wf_act_give_score_pp','effects','custom_effect'),
  ('wf_act_give_tag','effects','custom_effect'),
  ('wf_act_give_tag_perm','effects','custom_effect'),
  ('wf_act_give_take_furni_crew','effects','custom_effect'),
  ('wf_act_global_add_tag','effects','custom_effect'),
  ('wf_act_global_arithmetic','effects','custom_effect'),
  ('wf_act_global_remove_tag','effects','custom_effect'),
  ('wf_act_global_set_state_t_t','effects','custom_effect'),
  ('wf_act_global_set_tag_from_s','effects','custom_effect'),
  ('wf_act_init_transaction','effects','custom_effect'),
  ('wf_act_joue_assi','effects','custom_effect'),
  ('wf_act_joue_dorm','effects','custom_effect'),
  ('wf_act_joue_mute','effects','custom_effect'),
  ('wf_act_log','effects','custom_effect'),
  ('wf_act_make_say','effects','custom_effect'),
  ('wf_act_match_pos_noslide_cstm','effects','custom_effect'),
  ('wf_act_match_to_sshot','effects','custom_effect'),
  ('wf_act_match_triggered_furni','effects','custom_effect'),
  ('wf_act_move_rot_diagonal','effects','custom_effect'),
  ('wf_act_move_rotatb','effects','custom_effect'),
  ('wf_act_move_rotate_custom','effects','custom_effect'),
  ('wf_act_move_rotate_user','effects','custom_effect'),
  ('wf_act_move_rotnoz','effects','custom_effect'),
  ('wf_act_move_to_furni','effects','custom_effect'),
  ('wf_act_neg_log','effects','custom_effect'),
  ('wf_act_neg_show_message','effects','custom_effect'),
  ('wf_act_on_tag','effects','custom_effect'),
  ('wf_act_open_habbo_pages','effects','custom_effect'),
  ('wf_act_plus_match_furni_state','effects','custom_effect'),
  ('wf_act_plus_match_furni_state_instant','effects','custom_effect'),
  ('wf_act_pt_tele_furni_player_2','effects','custom_effect'),
  ('wf_act_quick_bopper','effects','custom_effect'),
  ('wf_act_remove_badge','effects','custom_effect'),
  ('wf_act_remove_furni_inventory','effects','custom_effect'),
  ('wf_act_remove_tag','effects','custom_effect'),
  ('wf_act_roller_speed','effects','custom_effect'),
  ('wf_act_send_bubble','effects','custom_effect'),
  ('wf_act_set_furni_opacity','effects','custom_effect'),
  ('wf_act_set_real_state','effects','custom_effect'),
  ('wf_act_set_roller_spd','effects','custom_effect'),
  ('wf_act_set_state','effects','custom_effect'),
  ('wf_act_set_state_from_tag','effects','custom_effect'),
  ('wf_act_set_tag_from_state','effects','custom_effect'),
  ('wf_act_show_tag','effects','custom_effect'),
  ('wf_act_super_wiredd','effects','custom_effect'),
  ('wf_act_tele_room','effects','custom_effect'),
  ('wf_act_teleport_blue','effects','custom_effect'),
  ('wf_act_teleport_bots_to_furni','effects','custom_effect'),
  ('wf_act_teleport_green','effects','custom_effect'),
  ('wf_act_teleport_red','effects','custom_effect'),
  ('wf_act_teleport_tu','effects','custom_effect'),
  ('wf_act_teleport_yellow','effects','custom_effect'),
  ('wf_act_tilss','effects','custom_effect'),
  ('wf_act_toggle_moodl','effects','custom_effect'),
  ('wf_act_toggle_moodlight','effects','custom_effect'),
  ('wf_act_toggle_state_down','effects','custom_effect'),
  ('wf_act_tour_ne_ava','effects','custom_effect'),
  ('wf_act_unfreeze','effects','custom_effect'),
  ('wf_act_unfreeze_habbo','effects','custom_effect'),
  ('wf_act_user_effect','effects','custom_effect'),
  ('wf_act_walkuser_alone','effects','custom_effect'),
  ('wf_cnd_actor_dir','conditions','habbo'),
  ('wf_cnd_actor_in_group','conditions','habbo'),
  ('wf_cnd_actor_in_team','conditions','habbo'),
  ('wf_cnd_chest_has_items','conditions','habbo'),
  ('wf_cnd_counter_time_matches','conditions','habbo'),
  ('wf_cnd_date_rng_active','conditions','habbo'),
  ('wf_cnd_furnis_hv_avtrs','conditions','habbo'),
  ('wf_cnd_has_altitude','conditions','habbo'),
  ('wf_cnd_has_furni_on','conditions','habbo'),
  ('wf_cnd_has_handitem','conditions','habbo'),
  ('wf_cnd_has_var','conditions','habbo'),
  ('wf_cnd_match_date','conditions','habbo'),
  ('wf_cnd_match_time','conditions','habbo'),
  ('wf_cnd_neg_has_var','conditions','habbo'),
  ('wf_cnd_not_furni_on','conditions','habbo'),
  ('wf_cnd_not_has_handitem','conditions','habbo'),
  ('wf_cnd_not_hv_avtrs','conditions','habbo'),
  ('wf_cnd_not_in_group','conditions','habbo'),
  ('wf_cnd_not_in_team','conditions','habbo'),
  ('wf_cnd_not_stuff_is','conditions','habbo'),
  ('wf_cnd_not_trggrer_on','conditions','habbo'),
  ('wf_cnd_not_triggerer_match','conditions','habbo'),
  ('wf_cnd_not_user_count','conditions','habbo'),
  ('wf_cnd_not_user_performs_action','conditions','habbo'),
  ('wf_cnd_not_wearing_b','conditions','habbo'),
  ('wf_cnd_not_wearing_fx','conditions','habbo'),
  ('wf_cnd_slc_quantity','conditions','habbo'),
  ('wf_cnd_stuff_is','conditions','habbo'),
  ('wf_cnd_team_has_rank','conditions','habbo'),
  ('wf_cnd_team_has_score','conditions','habbo'),
  ('wf_cnd_time_less_than','conditions','habbo'),
  ('wf_cnd_time_more_than','conditions','habbo'),
  ('wf_cnd_trggrer_on_frn','conditions','habbo'),
  ('wf_cnd_triggerer_match','conditions','habbo'),
  ('wf_cnd_user_count_in','conditions','habbo'),
  ('wf_cnd_user_performs_action','conditions','habbo'),
  ('wf_cnd_var_age_match','conditions','habbo'),
  ('wf_cnd_var_val_match','conditions','habbo'),
  ('wf_cnd_wearing_effect','conditions','habbo'),
  ('wf_cnd_atleast_one_user_team','conditions','custom_condition'),
  ('wf_cnd_attr_ibute_in','conditions','custom_condition'),
  ('wf_cnd_battlebanzai','conditions','custom_condition'),
  ('wf_cnd_chest_has_item_type','conditions','custom_condition'),
  ('wf_cnd_compare_tag_with_tag','conditions','custom_condition'),
  ('wf_cnd_comparison_tag','conditions','custom_condition'),
  ('wf_cnd_daily_trg','conditions','custom_condition'),
  ('wf_cnd_do_dont_have_furni_crew','conditions','custom_condition'),
  ('wf_cnd_freeze','conditions','custom_condition'),
  ('wf_cnd_freeze_booty','conditions','custom_condition'),
  ('wf_cnd_furnis_co_nnect','conditions','custom_condition'),
  ('wf_cnd_global_compare_t_t','conditions','custom_condition'),
  ('wf_cnd_habbo_has_credits','conditions','custom_condition'),
  ('wf_cnd_habbo_has_duckets','conditions','custom_condition'),
  ('wf_cnd_habbo_has_rank','conditions','custom_condition'),
  ('wf_cnd_habbo_is_dancing','conditions','custom_condition'),
  ('wf_cnd_habbo_not_owns_furni','conditions','custom_condition'),
  ('wf_cnd_habbo_not_rank','conditions','custom_condition'),
  ('wf_cnd_habbo_owns_furni','conditions','custom_condition'),
  ('wf_cnd_hdev_countavatars','conditions','custom_condition'),
  ('wf_cnd_hdev_stateis','conditions','custom_condition'),
  ('wf_cnd_is_dancingbb','conditions','custom_condition'),
  ('wf_cnd_item_state_cmp','conditions','custom_condition'),
  ('wf_cnd_lock','conditions','custom_condition'),
  ('wf_cnd_match_opacity','conditions','custom_condition'),
  ('wf_cnd_match_otheritm','conditions','custom_condition'),
  ('wf_cnd_match_snapshot','conditions','custom_condition'),
  ('wf_cnd_motto_contains','conditions','custom_condition'),
  ('wf_cnd_motto_contns','conditions','custom_condition'),
  ('wf_cnd_not_battlebanzai','conditions','custom_condition'),
  ('wf_cnd_not_battlebz','conditions','custom_condition'),
  ('wf_cnd_not_dancingb','conditions','custom_condition'),
  ('wf_cnd_not_freeze','conditions','custom_condition'),
  ('wf_cnd_not_freezebb','conditions','custom_condition'),
  ('wf_cnd_not_habbo_has_diamonds','conditions','custom_condition'),
  ('wf_cnd_not_habbo_is_dancing','conditions','custom_condition'),
  ('wf_cnd_not_has_altitude','conditions','custom_condition'),
  ('wf_cnd_not_match_opacity','conditions','custom_condition'),
  ('wf_cnd_not_match_otit','conditions','custom_condition'),
  ('wf_cnd_not_match_snap','conditions','custom_condition'),
  ('wf_cnd_not_users_x_points_cstm','conditions','custom_condition'),
  ('wf_cnd_select_furni_state','conditions','custom_condition'),
  ('wf_cnd_time_cool_down','conditions','custom_condition'),
  ('wf_cnd_trgr_stuff_matches','conditions','custom_condition'),
  ('wf_cnd_user_doesnt_have_tag','conditions','custom_condition'),
  ('wf_cnd_user_folow_ne','conditions','custom_condition'),
  ('wf_cnd_user_folow_po','conditions','custom_condition'),
  ('wf_cnd_user_group_in','conditions','custom_condition'),
  ('wf_cnd_user_group_ou','conditions','custom_condition'),
  ('wf_cnd_user_has_tag','conditions','custom_condition'),
  ('wf_cnd_user_in_range','conditions','custom_condition'),
  ('wf_cnd_user_not_in_range','conditions','custom_condition'),
  ('wf_cnd_user_on_furni_with_state','conditions','custom_condition'),
  ('wf_cnd_users_x_points_cstm','conditions','custom_condition'),
  ('wf_cnd_valid_moves','conditions','custom_condition'),
  ('wf_cnd_wearing_badge','conditions','custom_condition'),
  ('wf_cnd_x_habbos_with_tag','conditions','custom_condition');

-- La page cible : l'enfant 'habbo'/'custom' de la page de famille, sous la racine wired.
CREATE TEMPORARY TABLE wired_cible AS
SELECT t.class_name, sub.id AS page_id
FROM wired_tri t
JOIN catalog_pages root   ON root.localization = 'wired_furniture' AND root.deleted_at IS NULL
JOIN catalog_pages famille ON famille.parent_id = root.id AND famille.localization = t.famille AND famille.deleted_at IS NULL
JOIN catalog_pages sub    ON sub.parent_id = famille.id AND sub.localization = t.bucket AND sub.deleted_at IS NULL;

-- 1. Re-classer les offres wired déjà présentes dans la section.
UPDATE catalog_offers o
JOIN catalog_products p ON p.offer_id = o.id AND p.deleted_at IS NULL
JOIN furniture_definitions f ON f.id = p.definition_id
JOIN wired_cible c ON c.class_name = f.name
JOIN catalog_pages cur ON cur.id = o.page_id
JOIN catalog_pages fam2 ON fam2.id = cur.parent_id
JOIN catalog_pages root2 ON root2.id = fam2.parent_id AND root2.localization = 'wired_furniture'
SET o.page_id = c.page_id
WHERE o.deleted_at IS NULL AND o.page_id <> c.page_id;

-- 2. Créer l'offre manquante pour toute boîte qu'aucune page de la section ne vend.
CREATE TEMPORARY TABLE wired_manquants AS
WITH RECURSIVE section AS (
  SELECT id FROM catalog_pages WHERE localization = 'wired_furniture' AND deleted_at IS NULL
  UNION ALL SELECT ch.id FROM catalog_pages ch JOIN section s ON ch.parent_id = s.id WHERE ch.deleted_at IS NULL)
SELECT MIN(f.id) AS definition_id, f.name, f.type AS product_type, c.page_id
FROM furniture_definitions f
JOIN wired_cible c ON c.class_name = f.name
WHERE f.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM catalog_products p JOIN catalog_offers o ON o.id = p.offer_id
                  JOIN furniture_definitions f2 ON f2.id = p.definition_id
                  WHERE f2.name = f.name AND p.deleted_at IS NULL AND o.deleted_at IS NULL
                    AND o.visible = 1 AND o.page_id IN (SELECT id FROM section))
GROUP BY f.name, f.type, c.page_id;

INSERT INTO catalog_offers (page_id, localization_id, cost_credits, cost_currency, can_gift, can_bundle, club_level, visible)
SELECT page_id, name, 3, 0, 1, 1, 0, 1 FROM wired_manquants;

INSERT INTO catalog_products (offer_id, product_type, definition_id, quantity, unique_size, unique_remaining, builders_club_eligible)
SELECT o.id, m.product_type, m.definition_id, 1, 0, 0, 0
FROM wired_manquants m
JOIN catalog_offers o ON o.localization_id = m.name AND o.page_id = m.page_id
WHERE NOT EXISTS (SELECT 1 FROM catalog_products p WHERE p.offer_id = o.id);

DROP TEMPORARY TABLE wired_manquants; DROP TEMPORARY TABLE wired_cible; DROP TEMPORARY TABLE wired_tri;
