namespace Turbo.Revisions.Revision20260701;

internal static class MessageEvent
{
    // NEW since last revision
    public const int ClaimNftClaimsMessageEvent = 29;
    public const int GetNftClaimsMessageEvent = 3744;
    public const int GetNftStoreOffersMessageEvent = 3998;
    public const int NftStorePurchaseMessageEvent = 306;
    public const int GetRecyclerPrizesMessageEvent = 2516;
    public const int GetRecyclerStatusMessageEvent = 1246;
    public const int RecycleItemsMessageEvent = 2956;
    public const int AppealCfhMessageEvent = 1077;
    public const int GetCfhMyReportStatus = 275;
    public const int AddToCustomFilterMessageEvent = 936;
    public const int GetCustomFilterMessageEvent = 3812;
    public const int RemoveFromCustomFilterMessageEvent = 209;
    public const int WiredGetRoomLogsEvent = 706;
    public const int BlockListInitEvent = 2610;
    public const int BlockUserMessageEvent = 2371;
    public const int ReplenishRespectMessageEvent = 3323;
    public const int RespectUserMessageEvent = 3377;
    public const int UnblockUserMessageEvent = 1231;
    public const int AddNftToTradeEvent = 1543;
    public const int GetNftTradeInventoryEvent = 469;
    public const int RemoveNftFromTradeEvent = 1919;
    public const int WiredGetUserPermanentVariablesEvent = 2127;
    public const int WiredGetVariableOwnersPageEvent = 2221;
    public const int WiredSetUserPermanentVariableEvent = 2981;
    public const int ClaimDailyTaskEvent = 4101;
    public const int GetDailyTasksEvent = 4100;
    public const int ProgressTreasureHuntMessageEvent = 762;
    public const int ClickCharacterEvent = 785;
    public const int WiredClickUserMessageEvent = 3049;
    public const int WiredUpdateRoomEvent = 3814;

    #region Incoming

    public const int BreedPetsMessageEvent = 1922; // AS3-verified (ghost fix): AvatarInfoWidget::cancelBreedPets()
    public const int CustomizePetWithFurniEvent = 3327;
    public const int GetPetInfoMessageEvent = 2919;
    public const int PetSelectedMessageEvent = 3884;
    public const int RespectPetMessageEvent = 576;
    public const int ForwardToACompetitionRoomMessageEvent = 28;

    public const int
        ForwardToASubmittableRoomMessageEvent =
            9001; // UNRESOLVED: collided with CommunityGoalVoteMessageEvent after the WIN63-202607011411 client header remap; ForwardToASubmittableRoomMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int
        ForwardToRandomCompetitionRoomMessageEvent =
            9002; // UNRESOLVED: collided with RoomsWhereMyFriendsAreSearchMessageEvent after the WIN63-202607011411 client header remap; ForwardToRandomCompetitionRoomMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetCurrentTimingCodeMessageEvent = 1503;
    public const int GetIsUserPartOfCompetitionMessageEvent = 2732;
    public const int GetSecondsUntilMessageEvent = 1027;
    public const int RoomCompetitionInitMessageEvent = 3414;
    public const int SubmitRoomToCompetitionMessageEvent = 2579;
    public const int VoteForRoomMessageEvent = 45;
    public const int ResetPhoneNumberStateMessageEvent = 3591;
    public const int SetPhoneNumberVerificationStatusMessageEvent = 2445;
    public const int TryPhoneNumberMessageEvent = 3218;
    public const int VerifyCodeMessageEvent = 1372;
    public const int CommunityGoalVoteMessageEvent = 2055;
    public const int GetNftCreditsMessageEvent = 2069;

    public const int GetSelectedNftWardrobeOutfitMessageEvent = 3521; // AS3-verified: HabboAvatarEditor::sendGetSelectedNftWardrobeOutfitMessage()

    public const int GetSilverMessageEvent = 394;
    public const int GetUserNftWardrobeMessageEvent = 2203;
    public const int SaveUserNftWardrobeMessageEvent = 3428;
    public const int RoomNetworkOpenConnectionMessageEvent = 2045;
    public const int GetBotInventoryEvent = 3148;
    public const int GetCreditsInfoEvent = 540;
    public const int GetTalentTrackLevelMessageEvent = 1223;
    public const int GetTalentTrackMessageEvent = 3757;
    public const int GuideAdvertisementReadMessageEvent = 2673;
    public const int CallForHelpFromForumMessageMessageEvent = 2991;
    public const int CallForHelpFromForumThreadMessageEvent = 380;
    public const int CallForHelpFromIMMessageEvent = 838;
    public const int CallForHelpFromPhotoMessageEvent = 1964;
    public const int CallForHelpFromSelfieMessageEvent = 201;
    public const int CallForHelpMessageEvent = 732;
    public const int ChatReviewGuideDecidesOnOfferMessageEvent = 1638;
    public const int ChatReviewGuideDetachedMessageEvent = 2720;
    public const int ChatReviewGuideVoteMessageEvent = 1801; // AS3-verified (ghost fix): GuideSessionController::onGuardianChatReviewVoteEvent()
    public const int ChatReviewSessionCreateMessageEvent = 662;
    public const int DeletePendingCallsForHelpMessageEvent = 134;
    public const int GetCfhStatusMessageEvent = 1032;
    public const int GetGuideReportingStatusMessageEvent = 3755;

    public const int GetPendingCallsForHelpMessageEvent = 92; // AS3-verified: HabboHelp::queryForPendingCallsForHelp()

    public const int GetQuizQuestionsEvent = 554;
    public const int GuideSessionCreateMessageEvent = 3662;
    public const int GuideSessionFeedbackMessageEvent = 1394;
    public const int GuideSessionGetRequesterRoomMessageEvent = 2157;
    public const int GuideSessionGuideDecidesMessageEvent = 2776;
    public const int GuideSessionInviteRequesterMessageEvent = 2643;
    public const int GuideSessionIsTypingMessageEvent = 647;
    public const int GuideSessionMessageMessageEvent = 2505;
    public const int GuideSessionOnDutyUpdateMessageEvent = 958;
    public const int GuideSessionReportMessageEvent = 296;
    public const int GuideSessionRequesterCancelsMessageEvent = 937;
    public const int GuideSessionResolvedMessageEvent = 659;
    public const int PostQuizAnswersEvent = 1387;
    public const int ChangeQueueMessageEvent = 2704;
    public const int OpenFlatConnectionMessageEvent = 3234;
    public const int QuitMessageEvent = 3061;
    public const int BuildersClubPlaceRoomItemMessageEvent = 3849;
    public const int BuildersClubPlaceWallItemMessageEvent = 2740;
    public const int BuildersClubQueryFurniCountMessageEvent = 1739;
    public const int GetBonusRareInfoMessageEvent = 251;
    public const int GetBundleDiscountRulesetEvent = 2496;
    public const int GetBundleDiscountRulesetVortexEvent = 1811;
    public const int GetCatalogIndexEvent = 2232;
    public const int GetCatalogPageEvent = 2093;
    public const int GetCatalogPageWithEarliestExpiryEvent = 287;
    public const int GetClubGiftMessageEvent = 472;
    public const int GetClubGiftInfoRequestMessageEvent = 1422;
    public const int GetClubOffersMessageEvent = 667;
    public const int GetGiftWrappingConfigurationEvent = 1496;

    public const int
        GetGiftWrappingConfigurationVortexEvent =
            9008; // UNRESOLVED: collided with OpenCampaignCalendarDoorAsStaffEvent after the WIN63-202607011411 client header remap; GetGiftWrappingConfigurationVortexEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetHabboClubExtendOfferMessageEvent = 1808;
    public const int GetIsOfferGiftableEvent = 3892;
    public const int GetLimitedOfferAppearingNextEvent = 3682;

    public const int
        GetNextTargetedOfferEvent =
            9004; // UNRESOLVED: collided with CallForHelpFromForumMessageMessageEvent after the WIN63-202607011411 client header remap; GetNextTargetedOfferEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetProductOfferEvent = 1692;
    public const int GetRoomAdPurchaseInfoEvent = 876;
    public const int GetSeasonalCalendarDailyEvent = 341;
    public const int GetSellablePetPalettesEvent = 2626;
    public const int GetSnowWarGameTokensOfferEvent = 2447;
    public const int MarkCatalogNewAdditionsPageOpenedEvent = 3835; // AS3-verified (ghost fix): HabboCatalog::markNewAdditionPageOpened()
    public const int PurchaseBasicMembershipExtensionEvent = 3561;
    public const int PurchaseFromCatalogAsGiftEvent = 2909;
    public const int PurchaseFromCatalogEvent = 1706;
    public const int PurchaseRoomAdMessageEvent = 2928;
    public const int PurchaseSnowWarGameTokensOfferEvent = 3243;
    public const int PurchaseTargetedOfferEvent = 3916;
    public const int PurchaseVipMembershipExtensionEvent = 2441;
    public const int RedeemVoucherMessageEvent = 2779;
    public const int RoomAdPurchaseInitiatedEvent = 3607; // AS3-verified (ghost fix): HabboCatalog::sendRoomAdPurchaseInitiatedEvent()
    public const int SelectClubGiftEvent = 2087;
    public const int SetTargetedOfferStateEvent = 2796;
    public const int ShopTargetedOfferViewedEvent = 3888;
    public const int NavigatorAddCollapsedCategoryMessageEvent = 3920;
    public const int NavigatorAddSavedSearchEvent = 1188;
    public const int NavigatorDeleteSavedSearchEvent = 2444;
    public const int NavigatorRemoveCollapsedCategoryMessageEvent = 3449;
    public const int NavigatorSetSearchCodeViewModeMessageEvent = 3681;
    public const int NewNavigatorInitEvent = 1590;
    public const int NewNavigatorSearchEvent = 81;
    public const int GetOccupiedTilesMessageEvent = 3831;
    public const int GetRoomEntryTileMessageEvent = 9101; // UNRESOLVED: pre-existing value collided with the AS3-verified SetChatPreferencesMessageEvent (1149); GetRoomEntryTileMessageEvent's own value was already a mismatch before this pass (best AS3 candidate: onEntryTileData @ BCFloorPlanEditor, header 2792) - flagged for a future mismatch-fix pass
    public const int UpdateFloorPropertiesMessageEvent = 2937;
    public const int NewUserExperienceGetGiftsMessageEvent = 2314;
    public const int NewUserExperienceScriptProceedEvent = 2048;
    public const int SelectInitialRoomEvent = 1176;
    public const int GetInterstitialMessageEvent = 2689;
    public const int InterstitialShownMessageEvent = 1408;
    public const int CommandBotEvent = 15;
    public const int GetBotCommandConfigurationDataEvent = 1729;
    public const int GetBadgePointLimitsEvent = 981;
    public const int GetBadgesEvent = 770;
    public const int GetIsBadgeRequestFulfilledEvent = 2545;
    public const int RequestABadgeEvent = 3258;
    public const int SetActivatedBadgesEvent = 2764;
    public const int ResetUnseenItemIdsEvent = 1011;
    public const int ResetUnseenItemsEvent = 699;
    public const int AddAdminRightsToMemberMessageEvent = 660;
    public const int ApproveAllMembershipRequestsMessageEvent = 312;
    public const int ApproveMembershipRequestMessageEvent = 1347;
    public const int ApproveNameMessageEvent = 1211;
    public const int ChangeEmailEvent = 3706;
    public const int CreateGuildMessageEvent = 207;
    public const int DeactivateGuildMessageEvent = 53;
    public const int DeselectFavouriteHabboGroupMessageEvent = 306;
    public const int GetEmailStatusEvent = 2306;
    public const int GetExtendedProfileByNameMessageEvent = 321;
    public const int GetExtendedProfileMessageEvent = 847;
    public const int GetGuildCreationInfoMessageEvent = 831;
    public const int GetGuildEditInfoMessageEvent = 512;
    public const int GetGuildEditorDataMessageEvent = 3398; // AS3-verified (ghost fix): HabboGroupsManager::requestGuildEditorData()
    public const int GetGuildMembershipsMessageEvent = 3750;

    public const int
        GetGuildMembersMessageEvent =
            9007; // UNRESOLVED: collided with OpenFlatConnectionMessageEvent after the WIN63-202607011411 client header remap; GetGuildMembersMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetHabboGroupBadgesMessageEvent = 2767;
    public const int GetHabboGroupDetailsMessageEvent = 1683;
    public const int GetIgnoredUsersMessageEvent = 1026;
    public const int GetMemberGuildItemCountMessageEvent = 3677;
    public const int GetMOTDMessageEvent = 3163;
    public const int GetRelationshipStatusInfoMessageEvent = 3219;
    public const int GetSelectedBadgesMessageEvent = 3726;
    public const int GetUserNftChatStylesMessageEvent = 3642;
    public const int GiveStarGemToUserMessageEvent = -1; // REMOVED in 2026
    public const int IgnoreUserMessageEvent = 2070;
    public const int JoinHabboGroupMessageEvent = 1469;

    public const int
        KickMemberMessageEvent =
            9005; // UNRESOLVED: collided with CallForHelpFromForumThreadMessageEvent after the WIN63-202607011411 client header remap; KickMemberMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int RejectMembershipRequestMessageEvent = 2378;
    public const int RemoveAdminRightsFromMemberMessageEvent = 9102; // UNRESOLVED: pre-existing value collided with the AS3-verified AcceptQuestMessageEvent (985); RemoveAdminRightsFromMemberMessageEvent's own value was already a mismatch before this pass - flagged for a future mismatch-fix pass
    public const int ScrGetKickbackInfoMessageEvent = 1111;
    public const int ScrGetUserInfoMessageEvent = 1071;
    public const int SelectFavouriteHabboGroupMessageEvent = 1887;
    public const int UnblockGroupMemberMessageEvent = 1200;
    public const int UnignoreUserMessageEvent = 3542;
    public const int UpdateGuildBadgeMessageEvent = 3099;
    public const int UpdateGuildColorsMessageEvent = 3776;
    public const int UpdateGuildIdentityMessageEvent = 1630;
    public const int UpdateGuildSettingsMessageEvent = 3716; // AS3-verified (corrected ghost-fix): GuildManagementWindowCtrl -> _SafeCls_3380(groupId,guildType,rightsLevel), header 3716 (previous 2793 guess was a false positive matching a different forum-settings message)
    public const int CraftEvent = 169;
    public const int CraftSecretEvent = 146;
    public const int GetCraftableProductsEvent = 369; // AS3-verified (ghost fix): CraftingWidgetHandler::getCraftableProducts()
    public const int GetCraftingRecipeEvent = 1398; // AS3-verified (ghost fix): CraftingWidgetHandler::getCraftingRecipe()
    public const int GetCraftingRecipesAvailableEvent = 625;
    public const int CloseIssueDefaultActionMessageEvent = 1631;
    public const int CloseIssuesMessageEvent = 3986;
    public const int DefaultSanctionMessageEvent = 440;
    public const int GetCfhChatlogMessageEvent = 757;
    public const int GetModeratorRoomInfoMessageEvent = 3513;
    public const int GetModeratorUserInfoMessageEvent = 1948;
    public const int GetRoomChatlogMessageEvent = 3100;
    public const int GetRoomVisitsMessageEvent = 101;
    public const int GetUserChatlogMessageEvent = 3780;
    public const int ModAlertMessageEvent = 1861;
    public const int ModBanMessageEvent = 2507;
    public const int ModerateRoomMessageEvent = 2939;
    public const int ModeratorActionMessageEvent = 3230; // AS3-verified (ghost fix): ModerationMessageHandler::onModeratorActionResult()

    public const int
        ModKickMessageEvent =
            9010; // UNRESOLVED: collided with AvatarEffectSelectedEvent after the WIN63-202607011411 client header remap; ModKickMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int ModMessageMessageEvent = 2730;
    public const int ModMuteMessageEvent = 1788;

    public const int
        ModToolPreferencesEvent =
            9009; // UNRESOLVED: collided with GetExtendedProfileMessageEvent after the WIN63-202607011411 client header remap; ModToolPreferencesEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int ModToolSanctionEvent = 2010;
    public const int ModTradingLockMessageEvent = 3495;
    public const int PickIssuesMessageEvent = 3400;
    public const int ReleaseIssuesMessageEvent = 2932;
    public const int ClientHelloMessageEvent = 4000;
    public const int CompleteDiffieHandshakeMessageEvent = 2526;
    public const int DisconnectMessageEvent = 2864;
    public const int InfoRetrieveMessageEvent = 756;
    public const int InitDiffieHandshakeMessageEvent = 2022;
    public const int PongMessageEvent = 362;
    public const int SSOTicketMessageEvent = 882;
    public const int UniqueIDMessageEvent = 2309;
    public const int VersionCheckMessageEvent = 3584;
    public const int AcceptQuestMessageEvent = 985; // AS3-verified (ghost fix): QuestDetails::onAcceptQuest()
    public const int ActivateQuestMessageEvent = 555;
    public const int CancelQuestMessageEvent = 1221;
    public const int FriendRequestQuestCompleteMessageEvent = 480;
    public const int GetCommunityGoalHallOfFameMessageEvent = 2252;
    public const int GetCommunityGoalProgressMessageEvent = 1815;
    public const int GetConcurrentUsersGoalProgressMessageEvent = 2167;
    public const int GetConcurrentUsersRewardMessageEvent = 2451;
    public const int GetDailyQuestMessageEvent = 397;
    public const int GetQuestsMessageEvent = 2612;
    public const int GetSeasonalQuestsOnlyMessageEvent = 753;
    public const int OpenQuestTrackerMessageEvent = 155;
    public const int RejectQuestMessageEvent = 563;

    public const int
        StartCampaignMessageEvent =
            9011; // UNRESOLVED: collided with MyFavouriteRoomsSearchMessageEvent after the WIN63-202607011411 client header remap; StartCampaignMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetHotLooksMessageEvent = 3834; // AS3-verified (ghost fix): HotLooksModel::requestHotLooks()
    public const int ClickFurniMessageEvent = 443;
    public const int CompostPlantMessageEvent = 1989;
    public const int GetFurnitureAliasesMessageEvent = 1901;
    public const int GetRoomEntryDataMessageEvent = 1250;
    public const int GetItemDataMessageEvent = 204;
    public const int GetPetCommandsMessageEvent = 2425;
    public const int GiveSupplementToPetMessageEvent = 1694;
    public const int IssuePetCommandMessageEvent = 3072;
    public const int HarvestPetMessageEvent = 1210;
    public const int MountPetMessageEvent = 1996;
    public const int MoveAvatarMessageEvent = 2364;
    public const int MoveObjectMessageEvent = 1482;
    public const int MovePetMessageEvent = 2761;
    public const int MoveWallItemMessageEvent = 656;
    public const int PickupObjectMessageEvent = 1919;
    public const int PlaceBotMessageEvent = 1555;
    public const int PlaceObjectMessageEvent = 1974;
    public const int PlacePetMessageEvent = 314;
    public const int RemoveBotFromFlatMessageEvent = 2894;
    public const int RemoveItemMessageEvent = 2880;
    public const int RemovePetFromFlatMessageEvent = 418; // reverted: ghost-fix heuristic false positive (removeSaddleFromPet() legitimately belongs to RemoveSaddleFromPetMessageEvent) - still unresolved, needs a real AS3 trace
    public const int RemoveSaddleFromPetMessageEvent = 2884;
    public const int SetClothingChangeDataMessageEvent = 1220;
    public const int SetItemDataMessageEvent = 3498;
    public const int SetObjectDataMessageEvent = 246; // AS3-verified (ghost fix): InfoStandWidgetHandler::setObjectData()
    public const int TogglePetBreedingPermissionMessageEvent = 144;
    public const int TogglePetRidingPermissionMessageEvent = 3713;
    public const int UseFurnitureMessageEvent = 3353;
    public const int UseWallItemMessageEvent = 1540;
    public const int CreditVaultStatusMessageEvent = 1645;
    public const int IncomeRewardClaimMessageEvent = 809;
    public const int IncomeRewardStatusMessageEvent = 3417;
    public const int WithdrawCreditVaultMessageEvent = 1105;
    public const int OpenCampaignCalendarDoorAsStaffEvent = 3863;
    public const int OpenCampaignCalendarDoorEvent = 3643;
    public const int AcceptTradingEvent = 490;
    public const int AddItemsToTradeEvent = 3211;
    public const int AddItemToTradeEvent = 2177;
    public const int CloseTradingEvent = 3639;
    public const int ConfirmAcceptTradingEvent = 2662;
    public const int ConfirmDeclineTradingEvent = 1217;
    public const int OpenTradingEvent = 1865;
    public const int RemoveItemFromTradeEvent = 573;
    public const int SilverFeeMessageEvent = 2717; // AS3-verified (ghost fix): TradingModel::addSilverFee()
    public const int UnacceptTradingEvent = 1030;
    public const int UpdateFigureDataMessageEvent = 119;
    public const int AvatarExpressionMessageEvent = 2912;
    public const int ChangeMottoMessageEvent = 2659;
    public const int ChangePostureMessageEvent = 3181;

    public const int
        CustomizeAvatarWithFurniMessageEvent =
            9012; // UNRESOLVED: collided with GetUserEventCatsMessageEvent after the WIN63-202607011411 client header remap; CustomizeAvatarWithFurniMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int DanceMessageEvent = 48;
    public const int DropCarryItemMessageEvent = 3401;
    public const int LookToMessageEvent = 9103; // UNRESOLVED: pre-existing value collided with the AS3-verified ConfirmPetBreedingEvent (2872); LookToMessageEvent's own value was already a mismatch before this pass (best AS3 candidate: walkTo(), header 2364) - flagged for a future mismatch-fix pass
    public const int PassCarryItemMessageEvent = 2206;
    public const int PassCarryItemToPetMessageEvent = 149;
    public const int SignMessageEvent = 211;
    public const int Game2CheckGameDirectoryStatusMessageEvent = 1115;

    public const int
        Game2GetAccountGameStatusMessageEvent =
            9013; // UNRESOLVED: collided with RespectUserMessageEvent after the WIN63-202607011411 client header remap; Game2GetAccountGameStatusMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int Game2LeaveGameMessageEvent = 2698;
    public const int Game2QuickJoinGameMessageEvent = 2000;
    public const int Game2StartSnowWarMessageEvent = 2616;
    public const int GetForumsListMessageEvent = 488; // AS3-verified (ghost fix): GroupForumController::openForumsList()
    public const int GetForumStatsMessageEvent = 2632;

    public const int
        GetMessagesMessageEvent =
            9014; // UNRESOLVED: collided with OpenPetPackageMessageEvent after the WIN63-202607011411 client header remap; GetMessagesMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetThreadMessageEvent = 2367;
    public const int GetThreadsMessageEvent = 391;
    public const int GetUnreadForumsCountMessageEvent = 3589;
    public const int ModerateMessageMessageEvent = 2540;
    public const int ModerateThreadMessageEvent = 2138;
    public const int PostMessageMessageEvent = 2811;
    public const int UpdateForumReadMarkerMessageEvent = 3611;
    public const int UpdateForumSettingsMessageEvent = 1908;
    public const int UpdateThreadMessageEvent = 3206;
    public const int AddJukeboxDiskEvent = 3969;
    public const int GetJukeboxPlayListMessageEvent = 2379;
    public const int GetNowPlayingMessageEvent = 216;
    public const int GetOfficialSongIdMessageEvent = 3938;
    public const int GetSongInfoMessageEvent = 888;
    public const int GetSoundMachinePlayListMessageEvent = 675;
    public const int GetSoundSettingsEvent = 3141;
    public const int GetUserSongDisksMessageEvent = 1685; // AS3-verified (ghost fix): HabboMusicController::requestUserSongDisks()
    public const int RemoveJukeboxDiskEvent = 2896;
    public const int ChangeUserNameInRoomMessageEvent = 3652;
    public const int ChangeUserNameMessageEvent = 1703; // AS3-verified (ghost fix): NameChangeController::changeName()
    public const int CheckUserNameMessageEvent = 413; // AS3-verified (ghost fix): AvatarEditorMessageHandler::checkName()
    public const int GetWardrobeMessageEvent = 2210; // AS3-verified (ghost fix): AvatarEditorMessageHandler::getWardrobe()
    public const int SaveWardrobeOutfitMessageEvent = 3165;
    public const int BuyMarketplaceOfferMessageEvent = 252;
    public const int BuyMarketplaceTokensMessageEvent = 3419; // AS3-verified (ghost fix): MarketplaceModel::buyMarketplaceTokens()
    public const int CancelMarketplaceOfferMessageEvent = 2096;
    public const int GetMarketplaceCanMakeOfferMessageEvent = 2322;
    public const int GetMarketplaceConfigurationMessageEvent = 780;
    public const int GetMarketplaceItemStatsEvent = 1552;
    public const int GetMarketplaceOffersMessageEvent = 2731;
    public const int GetMarketplaceOwnOffersMessageEvent = 2086;
    public const int MakeOfferMessageEvent = 2375;
    public const int RedeemMarketplaceOfferCreditsMessageEvent = 3546;
    public const int GetAchievementsEvent = 2553;
    public const int AddSpamWallPostItMessageEvent = 2684;
    public const int ControlYoutubeDisplayPlaybackMessageEvent = 3024;
    public const int CreditFurniRedeemMessageEvent = 434;
    public const int DiceOffMessageEvent = 1558;
    public const int EnterOneWayDoorMessageEvent = 3293;
    public const int ExtendRentOrBuyoutFurniMessageEvent = 1427;
    public const int ExtendRentOrBuyoutStripItemMessageEvent = 3810;

    public const int
        GetGuildFurniContextMenuInfoMessageEvent =
            9015; // UNRESOLVED: collided with AddSpamWallPostItMessageEvent after the WIN63-202607011411 client header remap; GetGuildFurniContextMenuInfoMessageEvent has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int GetRentOrBuyoutOfferMessageEvent = 1583;
    public const int GetYoutubeDisplayStatusMessageEvent = 3635;
    public const int OpenMysteryTrophyMessageEvent = 3491;
    public const int OpenPetPackageMessageEvent = 1884;
    public const int PlacePostItMessageEvent = 174;
    public const int PresentOpenMessageEvent = 2485;
    public const int RentableSpaceCancelRentMessageEvent = 3941;
    public const int RentableSpaceConfigureMessageEvent = 4601;
    public const int RentableSpaceGetConfigMessageEvent = 4600;
    public const int RentableSpaceRentMessageEvent = 1165;
    public const int RentableSpaceStatusMessageEvent = 2542;
    public const int RoomDimmerChangeStateMessageEvent = 3894;
    public const int RoomDimmerGetPresetsMessageEvent = 3145;
    public const int RoomDimmerSavePresetMessageEvent = 130;
    public const int SetAreaHideDataEvent = 1954;
    public const int SetCustomStackingHeightEvent = 1682;
    public const int SetMannequinFigureEvent = 991;
    public const int SetMannequinNameEvent = 792;
    public const int SetRandomStateMessageEvent = 938;
    public const int SetRoomBackgroundColorDataEvent = 2019;
    public const int SetYoutubeDisplayPlaylistMessageEvent = 3622;
    public const int SpinWheelOfFortuneMessageEvent = 1010;
    public const int ThrowDiceMessageEvent = 93;
    public const int GetResolutionAchievementsMessageEvent = 995;
    public const int CancelPetBreedingEvent = 3367; // AS3-verified (ghost fix): AvatarInfoWidget::cancelPetBreeding()
    public const int ConfirmPetBreedingEvent = 2872; // AS3-verified (ghost fix): AvatarInfoWidget::confirmPetBreeding()
    public const int GetPetInventoryEvent = 3891;
    public const int EventLogMessageEvent = 3809;
    public const int LagWarningReportMessageEvent = 481;
    public const int LatencyPingReportMessageEvent = 1744;
    public const int LatencyPingRequestMessageEvent = 544;
    public const int PerformanceLogMessageEvent = 3983;
    public const int FriendFurniConfirmLockMessageEvent = 3523;
    public const int Game2MakeSnowballMessageEvent = 2604;
    public const int Game2RequestFullStatusUpdateMessageEvent = 3147;
    public const int Game2SetUserMoveTargetMessageEvent = 172;
    public const int Game2ThrowSnowballAtHumanMessageEvent = 3738;
    public const int Game2ThrowSnowballAtPositionMessageEvent = 2567;
    public const int AvatarEffectActivatedEvent = 3022;
    public const int AvatarEffectSelectedEvent = 2362;
    public const int AddFavouriteRoomMessageEvent = 3169;
    public const int CancelEventMessageEvent = 3402;
    public const int CanCreateRoomMessageEvent = 2617;
    public const int CompetitionRoomsSearchMessageEvent = 1307;
    public const int ConvertGlobalRoomIdMessageEvent = 584;
    public const int CreateFlatMessageEvent = 354;
    public const int DeleteFavouriteRoomMessageEvent = 1654;
    public const int EditEventMessageEvent = 2117;
    public const int ForwardToARandomPromotedRoomMessageEvent = 3551;
    public const int ForwardToSomeRoomMessageEvent = 3427;
    public const int GetGuestRoomMessageEvent = 2603;
    public const int GetOfficialRoomsMessageEvent = 3942;
    public const int GetPopularRoomTagsMessageEvent = 3214;
    public const int GetUserEventCatsMessageEvent = 3018;
    public const int GetUserFlatCatsMessageEvent = 235;
    public const int GuildBaseSearchMessageEvent = 3744;
    public const int MyFavouriteRoomsSearchMessageEvent = 2334;
    public const int MyFrequentRoomHistorySearchMessageEvent = 2174;
    public const int MyFriendsRoomsSearchMessageEvent = 1903;
    public const int MyGuildBasesSearchMessageEvent = 2224;
    public const int MyRecommendedRoomsMessageEvent = 184;
    public const int MyRoomHistorySearchMessageEvent = 632;
    public const int MyRoomRightsSearchMessageEvent = 1091;
    public const int MyRoomsSearchMessageEvent = 361;
    public const int PopularRoomsSearchMessageEvent = 2857;
    public const int RateFlatMessageEvent = 407;
    public const int RemoveOwnRoomRightsRoomMessageEvent = 260;
    public const int RoomAdEventTabAdClickedEvent = 759;
    public const int RoomAdEventTabViewedEvent = 3729;
    public const int RoomAdSearchMessageEvent = 1971;
    public const int RoomsWhereMyFriendsAreSearchMessageEvent = 2517;
    public const int RoomsWithHighestScoreSearchMessageEvent = 2135;
    public const int RoomTextSearchMessageEvent = 3487;
    public const int SetRoomSessionTagsMessageEvent = 3101;
    public const int ToggleStaffPickMessageEvent = 2985;
    public const int UpdateHomeRoomMessageEvent = 1817;
    public const int GetCollectibleMintableItemTypesMessageEvent = 36;
    public const int GetCollectibleMintingEnabledMessageEvent = 1554; // AS3-verified (ghost fix): MintInventoryListTab::onCollectibleMintingEnabledMessage()
    public const int GetCollectibleMintTokensMessageEvent = 2270;
    public const int GetCollectibleWalletAddressesMessageEvent = 261; // AS3-verified (ghost fix): CollectiblesView::requestWalletAddresses()
    public const int GetCollectorScoreMessageEvent = 2585;
    public const int GetMintTokenOffersMessageEvent = 238;
    public const int GetNftCollectionsMessageEvent = 3168;
    public const int GetNftTransferFeeMessageEvent = 1031;
    public const int MintItemMessageEvent = 37;
    public const int NftCollectiblesClaimBonusItemMessageEvent = 463;
    public const int NftCollectiblesClaimRewardItemMessageEvent = 1361;
    public const int NftTransferAssetsMessageEvent = 1646; // AS3-verified (ghost fix): CollectiblesModel::requestNftAssets()
    public const int PurchaseMintTokenMessageEvent = 2047;
    public const int PeerUsersClassificationMessageEvent = 628; // AS3-verified (ghost fix): RoomSession::sendPeerUsersClassificationMessage()
    public const int RoomUsersClassificationMessageEvent = 157; // AS3-verified (ghost fix): RoomSession::sendRoomUsersClassificationMessage()
    public const int MysteryBoxWaitingCanceledMessageEvent = 3661;
    public const int AmbassadorAlertMessageEvent = 3361;
    public const int AssignRightsMessageEvent = 373;
    public const int BanUserWithDurationMessageEvent = 120;
    public const int KickUserMessageEvent = 2748;
    public const int LetUserInMessageEvent = 963;
    public const int MuteAllInRoomEvent = 32;
    public const int MuteUserMessageEvent = 2339;
    public const int RemoveAllRightsMessageEvent = 159;
    public const int RemoveRightsMessageEvent = 3444;
    public const int UnbanUserFromRoomMessageEvent = 2804;
    public const int UnmuteUserMessageEvent = 498;
    public const int PollAnswerEvent = 3386;
    public const int PollRejectEvent = 1088;
    public const int PollStartEvent = 743;
    public const int DeleteRoomMessageEvent = 701;
    public const int GetBannedUsersFromRoomMessageEvent = 2702;
    public const int GetCustomRoomFilterMessageEvent = 790;
    public const int GetFlatControllersMessageEvent = 342;
    public const int GetRoomSettingsMessageEvent = 256;
    public const int SaveRoomSettingsMessageEvent = 725;
    public const int UpdateRoomCategoryAndTradeSettingsEvent = 3946;
    public const int UpdateRoomFilterMessageEvent = 1622;
    public const int RequestFurniInventoryEvent = 41;
    public const int RequestFurniInventoryWhenNotInRoomEvent = 3674;
    public const int RequestRoomPropertySet = 3300;
    public const int Game2GetFriendsLeaderboardEvent = 3467;
    public const int Game2GetTotalGroupLeaderboardEvent = 1479;
    public const int Game2GetTotalLeaderboardEvent = 3383;
    public const int Game2GetWeeklyFriendsLeaderboardEvent = 3867;
    public const int Game2GetWeeklyGroupLeaderboardEvent = 1480;
    public const int Game2GetWeeklyLeaderboardEvent = 1741;
    public const int CancelTypingMessageEvent = 2718;
    public const int ChatMessageEvent = 3034;
    public const int ShoutMessageEvent = 1763;
    public const int StartTypingMessageEvent = 2106;
    public const int WhisperMessageEvent = 1697;
    public const int WiredClearErrorLogsMessageEvent = 1002;
    public const int WiredGetAllVariableHoldersMessageEvent = 3907;
    public const int WiredGetAllVariablesDiffsMessageEvent = 797;
    public const int WiredGetAllVariablesHashMessageEvent = 3882;
    public const int WiredGetErrorLogsMessageEvent = 1825;
    public const int WiredGetRoomSettingsMessageEvent = 1028;
    public const int WiredGetRoomStatsMessageEvent = 3031;
    public const int WiredGetVariablesForObjectMessageEvent = 3466; // AS3-verified (ghost fix): WiredMenuInspectionTab::requestVariablesForObject()
    public const int WiredSetObjectVariableValueMessageEvent = 3657;
    public const int WiredSetPreferencesMessageEvent = 2278;
    public const int WiredSetRoomSettingsMessageEvent = 2881;
    public const int AcceptFriendMessageEvent = 1772;
    public const int DeclineFriendMessageEvent = 2778;
    public const int FindNewFriendsMessageEvent = 546;
    public const int FollowFriendMessageEvent = 886;
    public const int FriendListUpdateMessageEvent = 3679;
    public const int GetFriendRequestsMessageEvent = 3797;
    public const int GetMessengerHistoryEvent = 727;
    public const int HabboSearchMessageEvent = 3686;
    public const int MessengerInitMessageEvent = 3278;
    public const int RemoveFriendMessageEvent = 3005;
    public const int RequestFriendMessageEvent = 1;
    public const int SendMsgMessageEvent = 3357;
    public const int SendRoomInviteMessageEvent = 617;
    public const int SetRelationshipStatusMessageEvent = 1773;
    public const int VisitUserMessageEvent = 1515;
    public const int SetChatPreferencesMessageEvent = 1149; // AS3-verified (ghost fix): HabboFreeFlowChat::sendChatPreferences()
    public const int SetChatStylePreferenceEvent = 3964;
    public const int SetIgnoreRoomInvitesMessageEvent = 3617;
    public const int SetNewNavigatorWindowPreferencesMessageEvent = 1276;
    public const int SetRoomCameraPreferencesMessageEvent = 3914;
    public const int SetSoundSettingsEvent = 2608;
    public const int SetUIFlagsMessageEvent = 3653;
    public const int Game2ExitGameMessageEvent = 3510;
    public const int Game2GameChatMessageEvent = 3083;
    public const int Game2LoadStageReadyMessageEvent = 1320;
    public const int Game2PlayAgainMessageEvent = 855;
    public const int PhotoCompetitionMessageEvent = 3411;
    public const int PublishPhotoMessageEvent = 430;
    public const int PurchasePhotoMessageEvent = 1837;
    public const int RenderRoomMessageEvent = 538;
    public const int RequestCameraConfigurationMessageEvent = 1157;
    public const int GetPromoArticlesMessageEvent = 3152;
    public const int ApplySnapshotMessageEvent = 2790; // AS3-verified (ghost fix): UserDefinedRoomEventsCtrl::applySnapshot()
    public const int OpenMessageEvent = 3496;
    public const int UpdateActionMessageEvent = 148;
    public const int UpdateAddonMessageEvent = 2797;
    public const int UpdateConditionMessageEvent = 988;
    public const int UpdateSelectorMessageEvent = 510;
    public const int UpdateTriggerMessageEvent = 2669;
    public const int UpdateVariableMessageEvent = 1160;

    #endregion
}

internal static class MessageComposer
{
    // NEW since last revision
    public const int IncomeRewardNotificationMessageComposer = 1914;
    public const int GetCustomFilterResultMessageComposer = 1426;
    public const int ModifyCustomFilterResultMessageComposer = 1488;
    public const int FurniListRemoveMultipleComposer = 149;
    public const int LtdRaffleEnteredMessageComposer = 1221;
    public const int LtdRaffleResultMessageComposer = 3526;
    public const int WiredSetUserPermanentVariableResultComposer = 3354;
    public const int WiredUserPermanentVariablesComposer = 2883;
    public const int WiredUserVariablesListComposer = 3041;
    public const int NftClaimResultMessageComposer = 1780;
    public const int NftClaimsMessageComposer = 2053;
    public const int NftStoreOffersMessageComposer = 3585;
    public const int NftStorePurchaseMessageComposer = 3171;
    public const int RedeemNftLootBoxResultMessageComposer = 2262;
    public const int RedeemNftLootBoxStateMessageComposer = 2857;
    public const int NftEmeraldConvertResultMessageComposer = 3159;
    public const int TradeNftAssetInventoryMessageComposer = 3854;
    public const int TradeNftAssetsMessageComposer = 2159;
    public const int BlockListMessageComposer = 214;
    public const int BlockUserUpdateMessageComposer = 219;
    public const int DailyTasksActiveListMessageComposer = 2507;
    public const int DailyTasksTasksAddedMessageComposer = 1762;
    public const int DailyTasksTaskUpdateMessageComposer = 1065;
    public const int UserPurchasableChatStyleChangedMessageComposer = 2894;
    public const int UserPurchasableChatStylesMessageComposer = 2255;
    public const int BanInfoMessageComposer = 2557;
    public const int MyCfhReportStatusMessageComposer = 2474;
    public const int WiredRoomLogsComposer = 3761;
    public const int TreasureHuntFailMessageComposer = 3822;
    public const int TreasureHuntFirstWinnerMessageComposer = 1232;
    public const int TreasureHuntUpdateMessageComposer = 377;
    public const int RecyclerFinishedMessageComposer = 281;
    public const int RecyclerPrizesMessageComposer = 3783;
    public const int RecyclerStatusMessageComposer = 1919;
    public const int WiredClickUserResponseComposer = 2650;
    public const int WiredEnvironmentMessageComposer = 1186;

    #region Outgoing

    public const int CantConnectMessageComposer = 2430;
    public const int CloseConnectionMessageComposer = 3404;
    public const int FlatAccessibleMessageComposer = 2051;
    public const int GamePlayerValueMessageComposer = 1052;
    public const int HanditemConfigurationMessageComposer = 2942;
    public const int OpenConnectionMessageComposer = 611;
    public const int RoomForwardMessageComposer = 3339;
    public const int RoomQueueStatusMessageComposer = 530;
    public const int RoomReadyMessageComposer = 2349;
    public const int YouAreNotSpectatorMessageComposer = 412;
    public const int YouArePlayingGameMessageComposer = 1600;
    public const int YouAreSpectatorMessageComposer = 1901;
    public const int BotCommandConfigurationComposer = 2463; // AS3-verified (ghost fix): onBotCommandConfigurationEvent @ BotSkillConfigurationViewBase
    public const int BotErrorComposer = 520; // AS3-verified (ghost fix): onBotError @ RoomUsersHandler
    public const int BotForceOpenContextMenuComposer = 2336; // AS3-verified (ghost fix): onBotForceOpenContextMenuEvent @ RoomDesktop
    public const int BotSkillListUpdateComposer = 1293; // AS3-verified (ghost fix): onBotSkillListUpdateEvent @ RoomDesktop
    public const int AvailabilityStatusMessageComposer = 1350;
    public const int InfoHotelClosedMessageComposer = 3058;
    public const int InfoHotelClosingMessageComposer = 184;
    public const int LoginFailedHotelClosedMessageComposer = 698;
    public const int MaintenanceStatusMessageComposer = 1737;
    public const int NewUserExperienceGiftOfferComposer = 3307; // AS3-verified (ghost fix): onNewUserExperienceGiftOfferMessage @ HabboNuxDialogs
    public const int NewUserExperienceNotCompleteComposer = 752; // AS3-verified (ghost fix): onNewUserExperienceNotCompleteMessage @ HabboNuxDialogs
    public const int SelectInitialRoomComposer = 3624; // AS3-verified (ghost fix): onSelectInitialRoomResponse @ RoomPicker
    public const int JukeboxPlayListFullMessageComposer = 949; // AS3-verified (ghost fix): onJukeboxPlayListFullMessage @ JukeboxPlayListController
    public const int JukeboxSongDisksMessageComposer = 2257; // AS3-verified (ghost fix): onJukeboxSongDisksMessage @ JukeboxPlayListController
    public const int NowPlayingMessageComposer = 398; // AS3-verified (ghost fix): onNowPlayingMessage @ JukeboxPlayListController
    public const int OfficialSongIdMessageComposer = 2264;
    public const int PlayListMessageComposer = 1242;
    public const int PlayListSongAddedMessageComposer = 2785; // AS3-verified (ghost fix): onPlayListSongAddedMessage @ SoundMachinePlayListController
    public const int TraxSongInfoMessageComposer = 2278;
    public const int AchievementComposer = 3981; // AS3-verified (ghost fix): onAchievement
    public const int AchievementsComposer = 1969; // AS3-verified (ghost fix): onAchievements
    public const int AchievementsScoreComposer = 3070;
    public const int CampaignCalendarDataMessageComposer = 1028;
    public const int CampaignCalendarDoorOpenedMessageComposer = 2164;
    public const int BonusRareInfoMessageComposer = 3573;
    public const int BuildersClubFurniCountMessageComposer = 2378; // AS3-verified (ghost fix): onBuildersClubFurniCount @ HabboCatalog
    public const int BuildersClubSubscriptionStatusMessageComposer = 1893;
    public const int BundleDiscountRulesetMessageComposer = 1073; // AS3-verified (ghost fix): onBundleDiscountRulesetMessageEvent @ HabboCatalog
    public const int CatalogIndexMessageComposer = 3666;
    public const int CatalogPageMessageComposer = 1660;
    public const int CatalogPageWithEarliestExpiryMessageComposer = 3389;
    public const int CatalogPublishedMessageComposer = 773; // AS3-verified (ghost fix): onCatalogPublished @ HabboCatalog
    public const int ClubGiftInfoComposer = 3422;
    public const int ClubGiftSelectedComposer = 1842;

    public const int GiftReceiverNotFoundComposer = 2735; // AS3-verified: onGiftReceiverNotFound @ HabboCatalog

    public const int GiftWrappingConfigurationComposer = 1369;
    public const int HabboClubExtendOfferMessageComposer = 3689;
    public const int HabboClubOffersMessageComposer = 419;
    public const int IsOfferGiftableEventMessageComposer = 1750;
    public const int LimitedEditionSoldOutComposer = 533; // AS3-verified (ghost fix): onLimitedEditionSoldOut @ HabboCatalog
    public const int LimitedOfferAppearingNextMessageComposer = 1084;
    public const int NotEnoughBalanceMessageComposer = 1038;
    public const int ProductOfferComposer = 1911; // AS3-verified (ghost fix): onProductOffer @ HabboCatalog
    public const int PurchaseErrorMessageComposer = 1029;
    public const int PurchaseNotAllowedMessageComposer = 2493;
    public const int PurchaseOKMessageComposer = 1570;
    public const int RoomAdPurchaseInfoComposer = 3787;
    public const int SeasonalCalendarDailyOfferMessageComposer = 2775;
    public const int SellablePetPalettesMessageComposer = 3350; // AS3-verified (ghost fix): onSellablePalettes @ HabboCatalog
    public const int SnowWarGameTokensMessageComposer = 904;
    public const int TargetedOfferComposer = 2155; // AS3-verified (ghost fix): onTargetedOffer @ OfferController

    public const int TargetedOfferNotFoundComposer = 2013; // AS3-verified: onTargetedOfferNotFound @ OfferController

    public const int VoucherRedeemErrorMessageComposer = 133;
    public const int VoucherRedeemOkMessageComposer = 1771;
    public const int CallForHelpDisabledNotifyMessageComposer = 421; // AS3-verified (ghost fix): onCallForHelpDisabledNotify @ HabboHelp
    public const int CallForHelpPendingCallsMessageComposer = 678;
    public const int CallForHelpReplyMessageComposer = 2807; // AS3-verified (ghost fix): onCallForHelpReply @ CallForHelpManager
    public const int CallForHelpResultMessageComposer = 1930;
    public const int ChatReviewSessionDetachedMessageComposer = 645; // AS3-verified (ghost fix): onChatReviewSessionDetached @ GuideSessionController
    public const int ChatReviewSessionOfferedToGuideMessageComposer = 734; // AS3-verified (ghost fix): onChatReviewSessionOfferedToGuide @ GuideSessionController
    public const int ChatReviewSessionResultsMessageComposer = 508; // AS3-verified (ghost fix): onChatReviewSessionResults @ GuideSessionController
    public const int ChatReviewSessionStartedMessageComposer = 286; // AS3-verified (ghost fix): onChatReviewSessionStarted @ GuideSessionController
    public const int ChatReviewSessionVotingStatusMessageComposer = 1881; // AS3-verified (ghost fix): onChatReviewSessionVotingStatus @ GuideSessionController
    public const int GuideOnDutyStatusMessageComposer = 1923;
    public const int GuideReportingStatusMessageComposer = 3725; // AS3-verified (ghost fix): onGuideReportingStatus @ HabboHelp
    public const int GuideSessionAttachedMessageComposer = 3274;
    public const int GuideSessionDetachedMessageComposer = 2755; // AS3-verified (ghost fix): onGuideSessionDetached @ GuideSessionController
    public const int GuideSessionEndedMessageComposer = 2126; // AS3-verified (ghost fix): onGuideSessionEnded @ GuideSessionController
    public const int GuideSessionErrorMessageComposer = 2377; // AS3-verified (ghost fix): onGuideSessionError @ GuideSessionController
    public const int GuideSessionInvitedToGuideRoomMessageComposer = 776; // AS3-verified (ghost fix): onGuideSessionInvitedToGuideRoom @ GuideSessionController
    public const int GuideSessionMessageMessageComposer = 485; // AS3-verified (ghost fix): onGuideSessionMessage @ GuideSessionController
    public const int GuideSessionPartnerIsTypingMessageComposer = 3656; // AS3-verified (ghost fix): onGuideSessionPartnerIsTyping @ GuideSessionController
    public const int GuideSessionRequesterRoomMessageComposer = 2022; // AS3-verified (ghost fix): onGuideSessionRequesterRoom @ GuideSessionController
    public const int GuideSessionStartedMessageComposer = 3649;
    public const int IssueCloseNotificationMessageComposer = 3943; // AS3-verified (ghost fix): onIssueClose @ CallForHelpManager
    public const int QuizDataMessageComposer = 3999; // AS3-verified (ghost fix): onQuizData @ HabboWayQuizController
    public const int QuizResultsMessageComposer = 548; // AS3-verified (ghost fix): onQuizResults @ HabboWayQuizController
    public const int Game2EnterArenaFailedMessageComposer = 2158;
    public const int Game2GameEndingMessageComposer = 3446; // AS3-verified (ghost fix): onGameEnding
    public const int Game2GameRejoinMessageComposer = 1376; // AS3-verified (ghost fix): onRejoinGame
    public const int Game2StageStartingMessageComposer = 3295; // AS3-verified (ghost fix): onGameStageStarting @ HabboHelp
    public const int AreaHideMessageComposer = 1131; // AS3-verified (ghost fix): onAreaHide
    public const int CustomStackingHeightUpdateMessageComposer = 2552;

    public const int CustomUserNotificationMessageComposer = 169; // AS3-verified: onCustomUserNotificationMessage @ AvatarInfoWidgetHandler

    public const int DiceValueMessageComposer = 264; // AS3-verified (ghost fix): onDiceValue
    public const int FurniRentOrBuyoutOfferMessageComposer = 1127;
    public const int GuildFurniContextMenuInfoMessageComposer = 3220;
    public const int OneWayDoorStatusMessageComposer = 1778; // AS3-verified (ghost fix): onOneWayDoorStatus
    public const int OpenPetPackageRequestedMessageComposer = 3568;
    public const int OpenPetPackageResultMessageComposer = 716;
    public const int PresentOpenedMessageComposer = 914;
    public const int RentableSpaceConfigMessageComposer = 4600;
    public const int RentableSpaceRentFailedMessageComposer = 2954;
    public const int RentableSpaceRentOkMessageComposer = 2158; // AS3-verified (ghost fix): onRentableSpaceRentOkMessage
    public const int RentableSpaceStatusMessageComposer = 2800;
    public const int RequestSpamWallPostItMessageComposer = 1259;
    public const int RoomDimmerPresetsMessageComposer = 1093;
    public const int RoomMessageNotificationMessageComposer = 1740;
    public const int YoutubeControlVideoMessageComposer = 2958; // AS3-verified (ghost fix): onControlVideo
    public const int YoutubeDisplayPlaylistsMessageComposer = 807;
    public const int YoutubeDisplayVideoMessageComposer = 1227;
    public const int ErrorReportComposer = 1107;
    public const int TradeOpenFailedComposer = 2675;
    public const int TradeSilverFeeMessageComposer = 3497; // AS3-verified (ghost fix): onTradeSilverFee
    public const int TradeSilverSetMessageComposer = 2622;
    public const int TradingAcceptComposer = 560;
    public const int TradingCloseComposer = 699;
    public const int TradingCompletedComposer = 1070;
    public const int TradingConfirmationComposer = 3138;
    public const int TradingItemListComposer = 2275;
    public const int TradingNotOpenComposer = 3556;
    public const int TradingOpenComposer = 953;
    public const int TradingOtherNotAllowedComposer = 949;
    public const int TradingYouAreNotAllowedComposer = 1116;
    public const int MarketplaceBuyOfferResultComposer = 2249;
    public const int MarketplaceCancelOfferResultComposer = 2448;
    public const int MarketplaceCanMakeOfferResult = 1077;
    public const int MarketplaceConfigurationComposer = 1397;
    public const int MarketplaceItemStatsComposer = 2821;
    public const int MarketplaceMakeOfferResult = 2471;
    public const int MarketPlaceOffersComposer = 2442;
    public const int MarketPlaceOwnOffersComposer = 88;
    public const int PerkAllowancesMessageComposer = 1535;
    public const int RoomEntryTileMessageComposer = 2792;
    public const int RoomOccupiedTilesMessageComposer = 1373;
    public const int HotLooksMessageComposer = 3853; // AS3-verified (ghost fix): onHotLooksMessage @ HotLooksModel
    public const int CreditBalanceComposer = 3642;
    public const int AvatarEffectMessageComposer = 3629;
    public const int CarryObjectMessageComposer = 2850;
    public const int DanceMessageComposer = 2217;
    public const int ExpressionMessageComposer = 1036;
    public const int SleepMessageComposer = 3517;
    public const int UseObjectMessageComposer = 1953;
    public const int Game2AccountGameStatusMessageComposer = 683;
    public const int Game2GameCancelledMessageComposer = 2334;
    public const int Game2GameCreatedMessageComposer = 413; // AS3-verified (ghost fix): onGameCreated
    public const int Game2GameDirectoryStatusMessageComposer = 3251;
    public const int Game2GameLongDataMessageComposer = 3539; // AS3-verified (ghost fix): onGameLongData
    public const int Game2GameStartedMessageComposer = 2902; // AS3-verified (ghost fix): onGameStarted
    public const int Game2InArenaQueueMessageComposer = 2756;
    public const int Game2JoiningGameFailedMessageComposer = 493;
    public const int Game2StartCounterMessageComposer = 2008;
    public const int Game2StartingGameFailedMessageComposer = 1140;
    public const int Game2StopCounterMessageComposer = 2747;
    public const int Game2UserBlockedMessageComposer = 1145;
    public const int Game2UserLeftGameMessageComposer = 606;
    public const int ChangeUserNameResultMessageComposer = 1621;
    public const int CheckUserNameResultMessageComposer = 2802;
    public const int FigureUpdateComposer = 132;
    public const int WardrobeMessageComposer = 1484; // AS3-verified (ghost fix): onWardrobe @ AvatarEditorMessageHandler

    public const int CollectableMintableItemTypesMessageComposer = 1902; // AS3-verified: onCollectableMintableItemTypesMessage @ MintInventoryListTab

    public const int CollectibleMintableItemResultMessageComposer = 2657;
    public const int CollectibleMintingEnabledMessageComposer = 1091; // AS3-verified (ghost fix): onCollectibleMintingEnabledMessage @ MintInventoryListTab
    public const int CollectibleMintTokenCountMessageComposer = 3419;
    public const int CollectibleMintTokenOffersMessageComposer = 2462; // AS3-verified (ghost fix): onMintTokenOffersMessage @ MintInventoryListTab
    public const int CollectibleWalletAddressesMessageComposer = 2162;
    public const int EmeraldBalanceMessageComposer = 583; // AS3-verified (ghost fix): onEmeraldBalance @ HabboCatalog
    public const int NftBonusItemClaimResultMessageComposer = 2138;
    public const int NftCollectionsMessageComposer = 3942; // AS3-verified (ghost fix): onNftCollectionsMessage @ CollectionsTab
    public const int NftCollectionsScoreMessageComposer = 1801;
    public const int NftRewardItemClaimResultMessageComposer = 878;
    public const int NftTransferAssetsResultMessageComposer = 3853;
    public const int NftTransferFeeMessageComposer = 3700; // AS3-verified (ghost fix): onNftTransferFeeMessage @ TransferNftsTab
    public const int SilverBalanceMessageComposer = 3727; // AS3-verified (ghost fix): onSilverBalance @ HabboCatalog
    public const int AcceptFriendResultComposer = 3407;
    public const int ConsoleMessageHistoryComposer = 933;
    public const int FindFriendsProcessResultComposer = 2642;
    public const int FollowFriendFailedComposer = 240;
    public const int FriendListFragmentMessageComposer = 2641;
    public const int FriendListUpdateComposer = 3611;
    public const int FriendNotificationComposer = 2094;
    public const int FriendRequestsComposer = 1120;
    public const int HabboSearchResultComposer = 2637;
    public const int InstantMessageErrorComposer = 3501;
    public const int MessengerErrorComposer = 358;
    public const int MessengerInitComposer = 1590;
    public const int MiniMailNewMessageComposer = 667;
    public const int MiniMailUnreadCountComposer = 74; // AS3-verified (ghost fix): onMiniMailUnreadCount @ HabboMessenger
    public const int NewConsoleMessageComposer = 468;
    public const int NewFriendRequestComposer = 1860;
    public const int RoomInviteErrorComposer = 3065;
    public const int RoomInviteComposer = 3194;
    public const int InterstitialMessageComposer = 3898;
    public const int RoomAdErrorComposer = 2396;
    public const int ForumDataMessageComposer = 3965; // AS3-verified (ghost fix): onForumData @ GroupForumController
    public const int ForumsListMessageComposer = 1373; // AS3-verified (ghost fix): onForumsList @ GroupForumController
    public const int ForumThreadsMessageComposer = 1831;
    public const int PostMessageMessageComposer = 2475; // AS3-verified (ghost fix): onPostMessageMessage @ GroupForumController

    public const int PostThreadMessageComposer = 956; // AS3-verified: onPostThreadMessage @ GroupForumController

    public const int ThreadMessagesMessageComposer = 3481;
    public const int UnreadForumsCountMessageComposer = 3942;
    public const int UpdateMessageMessageComposer = 2988; // AS3-verified (ghost fix): onUpdateMessage @ GroupForumController
    public const int UpdateThreadMessageComposer = 1146; // AS3-verified (ghost fix): onUpdateThread @ GroupForumController
    public const int CreditVaultStatusMessageComposer = -1; // REMOVED in 2026
    public const int IncomeRewardClaimResponseMessageComposer = 2984;
    public const int IncomeRewardStatusMessageComposer = 3976;
    public const int BotAddedToInventoryComposer = 3294;
    public const int BotInventoryComposer = 682;
    public const int BotRemovedFromInventoryComposer = 2170;
    public const int BadgePointLimitsComposer = 3510; // AS3-verified (ghost fix): onBadgePointLimits
    public const int BadgeReceivedComposer = 2840; // AS3-verified (ghost fix): onBadgeReceived
    public const int BadgesComposer = 2748;
    public const int IsBadgeRequestFulfilledComposer = 2295;
    public const int NavigatorCollapsedCategoriesMessageComposer = 1754;
    public const int NavigatorLiftedRoomsComposer = 1761;
    public const int NavigatorMetaDataComposer = 24;
    public const int NavigatorSavedSearchesComposer = 866;
    public const int NavigatorSearchResultBlocksComposer = 3708;
    public const int NewNavigatorPreferencesComposer = 3937;
    public const int BannedUsersFromRoomComposer = 845;
    public const int FlatControllerAddedComposer = 1359;
    public const int FlatControllerRemovedComposer = 3335;
    public const int FlatControllersComposer = 726;
    public const int NoSuchFlatComposer = 1122; // AS3-verified (ghost fix): onNoSuchFlat
    public const int RoomSettingsDataComposer = 791;
    public const int RoomSettingsErrorComposer = 3715; // AS3-verified (ghost fix): onRoomSettingsError
    public const int RoomSettingsSavedComposer = 1783;
    public const int RoomSettingsSaveErrorComposer = 879;
    public const int ShowEnforceRoomCategoryDialogComposer = 2944;
    public const int UserUnbannedFromRoomComposer = 2089;
    public const int PollContentsComposer = 1297;
    public const int PollErrorComposer = 969;
    public const int PollOfferComposer = 579;
    public const int QuestionAnsweredComposer = 1659;
    public const int QuestionComposer = 2157;
    public const int QuestionFinishedComposer = 2108;
    public const int Game2FullGameStatusMessageComposer = 1739; // AS3-verified (ghost fix): onFullGameStatus
    public const int CompetitionEntrySubmitResultMessageComposer = 3222;
    public const int CompetitionVotingInfoMessageComposer = 2617; // AS3-verified (ghost fix): onCompetitionVotingInfo
    public const int CurrentTimingCodeMessageComposer = 3076;
    public const int NoOwnedRoomsAlertMessageComposer = 735; // AS3-verified (ghost fix): onNoOwnedRoomsAlert
    public const int SecondsUntilMessageComposer = 1557;
    public const int CfhChatlogComposer = 3880; // AS3-verified (ghost fix): onCfhChatlog @ ModerationMessageHandler
    public const int IssueDeletedMessageComposer = 122; // AS3-verified (ghost fix): onIssueDeleted @ ModerationMessageHandler

    public const int IssueInfoMessageComposer = 3585; // AS3-verified: onIssueInfo @ ModerationMessageHandler (== its ORIGINAL pre-fix value - was never actually wrong)

    public const int IssuePickFailedMessageComposer = 940;
    public const int ModeratorActionResultMessageComposer = 2960; // AS3-verified (ghost fix): onModeratorActionResult @ ModerationMessageHandler
    public const int ModeratorCautionComposer = 2619;
    public const int ModeratorInitMessageComposer = 757; // AS3-verified (ghost fix): onModeratorInit @ ModerationMessageHandler
    public const int ModeratorMessageComposer = 3885;
    public const int ModeratorToolPreferencesComposer = 1898; // AS3-verified (ghost fix): onModeratorToolPreferences @ ModerationMessageHandler
    public const int ModeratorUserInfoComposer = 2589; // AS3-verified (ghost fix): onUserInfo @ ModerationMessageHandler
    public const int RoomChatlogComposer = 2886; // AS3-verified (ghost fix): onRoomChatlog @ ModerationMessageHandler
    public const int RoomVisitsComposer = 497; // AS3-verified (ghost fix): onRoomVisits @ ModerationMessageHandler
    public const int UserBannedMessageComposer = 3621;
    public const int UserChatlogComposer = 3732; // AS3-verified (ghost fix): onUserChatlog @ ModerationMessageHandler

    public const int CraftableProductsMessageComposer = 3155; // AS3-verified: onCraftableProductsMessage @ CraftingWidgetHandler

    public const int CraftingRecipeMessageComposer = 425; // AS3-verified (ghost fix): onCraftingRecipeMessage @ CraftingWidgetHandler
    public const int CraftingRecipesAvailableMessageComposer = 3282; // AS3-verified (ghost fix): onCraftingRecipesAvailableMessage @ CraftingWidgetHandler
    public const int CraftingResultMessageComposer = 2999; // AS3-verified (ghost fix): onCraftingResultMessage @ CraftingWidgetHandler
    public const int ChatMessageComposer = 311;
    public const int FloodControlMessageComposer = 3614; // AS3-verified (ghost fix): onFloodControl @ RoomChatHandler
    public const int RemainingMutePeriodComposer = 2129; // AS3-verified (ghost fix): onRemainingMutePeriod @ RoomChatHandler
    public const int RoomChatSettingsMessageComposer = 594; // AS3-verified (ghost fix): onRoomChatSettings @ HabboFreeFlowChat
    public const int RoomFilterSettingsMessageComposer = 3208; // AS3-verified (ghost fix): onRoomFilterSettings
    public const int ShoutMessageComposer = 1776;
    public const int UserTypingMessageComposer = 206;
    public const int WhisperMessageComposer = 3072;
    public const int ConfirmBreedingRequestComposer = 730;
    public const int ConfirmBreedingResultComposer = 999;
    public const int GoToBreedingNestFailureComposer = 2441; // AS3-verified (ghost fix): onGoToBreedingNestFailure

    public const int NestBreedingSuccessComposer = 40; // AS3-verified: onNestBreedingSuccess @ RoomUsersHandler

    public const int PetAddedToInventoryComposer = 1951;
    public const int PetBreedingComposer = 939; // AS3-verified (ghost fix): onPetBreedingEvent @ RoomUsersHandler
    public const int PetInventoryComposer = 1200;
    public const int PetReceivedMessageComposer = 1692;
    public const int PetRemovedFromInventoryComposer = 2570;
    public const int CameraPublishStatusMessageComposer = 203; // AS3-verified (ghost fix): onPublishStatus @ CameraWidgetHandler
    public const int CameraPurchaseOKMessageComposer = 3869;
    public const int CameraStorageUrlMessageComposer = 2176; // AS3-verified (ghost fix): onCameraStorageUrlEvent @ CameraWidgetHandler
    public const int CompetitionStatusMessageComposer = 2622; // AS3-verified (ghost fix): onCompetitionStatus @ CameraWidgetHandler
    public const int InitCameraMessageComposer = 2768; // AS3-verified (ghost fix): onInitCameraEvent @ CameraWidgetHandler
    public const int ThumbnailStatusMessageComposer = 3707;
    public const int CancelMysteryBoxWaitMessageComposer = 2677;
    public const int GotMysteryBoxPrizeMessageComposer = 353; // AS3-verified (ghost fix): onGotMysteryBoxPrize @ MysteryBoxOpenDialogView
    public const int MysteryBoxKeysMessageComposer = 1389;
    public const int ShowMysteryBoxWaitMessageComposer = 691; // AS3-verified (ghost fix): onShowMysteryBoxWait @ MysteryBoxOpenDialogView
    public const int WiredAllVariableHoldersComposer = 3506; // AS3-verified (ghost fix): onAllVariableHolders @ WiredMenuOverviewTab
    public const int WiredAllVariablesDiffsComposer = 2733;
    public const int WiredAllVariablesHashComposer = 3287; // AS3-verified (ghost fix): onAllVariablesHashEvent @ WiredVariablesSynchronizer
    public const int WiredErrorLogsComposer = 2032;
    public const int WiredMenuErrorComposer = 1741;
    public const int WiredPermissionsComposer = 2913;
    public const int WiredRoomSettingsComposer = 1376;
    public const int WiredRoomStatsComposer = 1964; // AS3-verified (ghost fix): onRoomStatsEvent @ WiredMenuMonitorTab
    public const int WiredVariablesForObjectComposer = 2179; // AS3-verified (ghost fix): onWiredVariablesForObject @ WiredMenuInspectionTab
    public const int AuthenticationOKMessageComposer = 230;
    public const int CompleteDiffieHandshakeComposer = 3401;
    public const int DisconnectReasonComposer = 4000;
    public const int GenericErrorComposer = 297;
    public const int IdentityAccountsComposer = 1343;
    public const int InitDiffieHandshakeComposer = 3309;
    public const int IsFirstLoginOfDayComposer = 2313;
    public const int NoobnessLevelMessageComposer = 3913;
    public const int PingMessageComposer = 1407;
    public const int UniqueMachineIDComposer = 1973;
    public const int UserObjectComposer = 3985;
    public const int UserRightsMessageComposer = 3599;
    public const int CommunityVoteReceivedComposer = 2524;
    public const int UserNftChatStylesMessageComposer = 2996;
    public const int UserNftWardrobeSelectionMessageComposer = 582;
    public const int LatencyPingResponseMessageComposer = 188;
    public const int CommunityGoalHallOfFameMessageComposer = 363;
    public const int CommunityGoalProgressMessageComposer = 283;
    public const int ConcurrentUsersGoalProgressMessageComposer = 1003;
    public const int EpicPopupMessageComposer = 3295;
    public const int QuestCancelledMessageComposer = 1425; // AS3-verified (ghost fix): onQuestCancelled
    public const int QuestCompletedMessageComposer = 3497;
    public const int QuestDailyMessageComposer = 1417;
    public const int QuestMessageComposer = 54; // AS3-verified (ghost fix): onQuest
    public const int QuestsMessageComposer = 3398; // AS3-verified (ghost fix): onQuests
    public const int SeasonalQuestsMessageComposer = 1390; // AS3-verified (ghost fix): onSeasonalQuests
    public const int ActivityPointsMessageComposer = 509;
    public const int ClubGiftNotificationComposer = 1023;
    public const int ElementPointerMessageComposer = 1807;
    public const int HabboAchievementNotificationMessageComposer = 639;
    public const int HabboActivityPointNotificationMessageComposer = 2046; // AS3-verified (ghost fix): onActivityPointNotification @ HabboCatalog
    public const int HabboBroadcastMessageComposer = 334;
    public const int InfoFeedEnableMessageComposer = 1936;
    public const int MOTDNotificationComposer = 1330;
    public const int NotificationDialogMessageComposer = 2243;
    public const int OfferRewardDeliveredMessageComposer = 2621; // AS3-verified (ghost fix): onOfferRewardDelivered @ OfferCenter
    public const int PetLevelNotificationComposer = 1702;
    public const int RestoreClientMessageComposer = 3345;
    public const int UnseenItemsComposer = 3059;
    public const int PetBreedingResultComposer = 2940;
    public const int PetCommandsMessageComposer = 3811;
    public const int PetExperienceComposer = 946; // AS3-verified (ghost fix): onPetExperience
    public const int PetFigureUpdateComposer = 3796;
    public const int PetInfoMessageComposer = 3192;
    public const int PetLevelUpdateComposer = 3104; // AS3-verified (ghost fix): onPetLevelUpdate @ RoomUsersHandler
    public const int PetPlacingErrorComposer = 3195; // AS3-verified (ghost fix): onPetPlacingError @ RoomUsersHandler
    public const int PetRespectFailedComposer = 31;
    public const int PetStatusUpdateComposer = 2753;
    public const int PetVocalComposer = 3073;
    public const int AchievementResolutionCompletedMessageComposer = 1166; // AS3-verified (ghost fix): onAchievementResolutionCompleted
    public const int AchievementResolutionProgressMessageComposer = 1844;
    public const int AchievementResolutionsMessageComposer = 3143; // AS3-verified (ghost fix): onAchievementResolutions

    public const int TryPhoneNumberResultMessageComposer = 2845; // AS3-verified: onPhoneNumberResultMessage @ HabboPhoneNumber

    public const int TryVerificationCodeResultMessageComposer = 712; // AS3-verified (ghost fix): onVerificationCodeResultMessage @ HabboPhoneNumber
    public const int FigureSetIdsComposer = 1231;
    public const int AccountPreferencesComposer = 724;
    public const int Game2FriendsLeaderboardComposer = 2272;
    public const int Game2TotalGroupLeaderboardComposer = 2417;
    public const int Game2TotalLeaderboardComposer = 733;


    public const int Game2WeeklyGroupLeaderboardComposer = 2876;
    public const int Game2WeeklyLeaderboardComposer = 273;
    public const int CfhSanctionMessageComposer = 3119;
    public const int CfhTopicsInitMessageComposer = 1762; // AS3-verified (ghost fix): onCfhTopics @ HabboHelp
    public const int SanctionStatusComposer = 3113;
    public const int YouAreControllerMessageComposer = 934;
    public const int YouAreNotControllerMessageComposer = 456;
    public const int YouAreOwnerMessageComposer = 1986;
    public const int AvatarEffectActivatedMessageComposer = 3814; // AS3-verified (ghost fix): onAvatarEffectActivated @ AvatarEditorMessageHandler
    public const int AvatarEffectAddedMessageComposer = 1577; // AS3-verified (ghost fix): onAvatarEffectAdded @ AvatarEditorMessageHandler
    public const int AvatarEffectExpiredMessageComposer = 2236; // AS3-verified (ghost fix): onAvatarEffectExpired @ AvatarEditorMessageHandler
    public const int AvatarEffectSelectedMessageComposer = 3629; // AS3-verified (ghost fix): onAvatarEffectSelected @ AvatarEditorMessageHandler
    public const int AvatarEffectsMessageComposer = 2405;
    public const int TalentLevelUpMessageComposer = 1564; // AS3-verified (ghost fix): onTalentLevelUp @ TalentLevelUpController
    public const int TalentTrackLevelMessageComposer = 2210; // AS3-verified (ghost fix): onTalentTrackLevel @ TalentPromoCtrl
    public const int TalentTrackMessageComposer = 3909; // AS3-verified (ghost fix): onTalentTrack @ TalentTrackController
    public const int AccountSafetyLockStatusChangeMessageComposer = 70;
    public const int ApproveNameMessageComposer = 1879;
    public const int ChangeEmailResultComposer = 3909;
    public const int EmailStatusResultComposer = 2343;
    public const int ExtendedProfileChangedMessageComposer = 3369;
    public const int ExtendedProfileMessageComposer = 1918;
    public const int GroupDetailsChangedMessageComposer = 12;
    public const int GuildCreatedMessageComposer = 2138; // AS3-verified (ghost fix): onGuildCreated @ HabboGroupsManager
    public const int GuildCreationInfoMessageComposer = 973; // AS3-verified (ghost fix): onGuildCreationInfo @ HabboGroupsManager
    public const int GuildEditFailedMessageComposer = 496; // AS3-verified (ghost fix): onGuildEditFailed @ HabboGroupsManager
    public const int GuildEditInfoMessageComposer = 1288; // AS3-verified (ghost fix): onGuildEditInfo @ HabboGroupsManager
    public const int GuildEditorDataMessageComposer = 1132; // AS3-verified (ghost fix): onGuildEditorData @ HabboGroupsManager
    public const int GuildMemberFurniCountInHQMessageComposer = 1770;
    public const int GuildMemberMgmtFailedMessageComposer = 3758;
    public const int GuildMembershipRejectedMessageComposer = 2521;
    public const int GuildMembershipsMessageComposer = 3994; // AS3-verified (ghost fix): onGuildMemberships @ HabboCatalog
    public const int GuildMembershipUpdatedMessageComposer = 829;
    public const int GuildMembersMessageComposer = 1895;
    public const int HabboGroupBadgesMessageComposer = 1400;
    public const int HabboGroupDeactivatedMessageComposer = 2087;
    public const int HabboGroupDetailsMessageComposer = 2847;
    public const int HabboGroupJoinFailedMessageComposer = 3356;
    public const int HabboUserBadgesMessageComposer = 1292;
    public const int HandItemReceivedMessageComposer = 3874;
    public const int IgnoredUsersMessageComposer = 191;
    public const int IgnoreResultMessageComposer = 253;
    public const int InClientLinkMessageComposer = 1554;
    public const int PetRespectNotificationComposer = 1784;
    public const int PetSupplementedNotificationComposer = 3858; // AS3-verified (ghost fix): onPetSupplementedNotification @ RoomChatHandler
    public const int RelationshipStatusInfoComposer = 3360;
    public const int RespectNotificationMessageComposer = 2686;
    public const int ScrSendKickbackInfoMessageComposer = 3887;
    public const int ScrSendUserInfoComposer = 1097;
    public const int UserNameChangedMessageComposer = 2319;
    public const int PromoArticlesMessageComposer = 1082;
    public const int BuildersClubPlacementWarningMessageComposer = 2458;
    public const int FavoriteMembershipUpdateMessageComposer = 233;
    public const int FloorHeightMapMessageComposer = 2885;
    public const int FurnitureAliasesMessageComposer = 154;
    public const int HeightMapMessageComposer = 2260;
    public const int HeightMapUpdateMessageComposer = 3279;
    public const int ItemAddMessageComposer = 3733;
    public const int ItemDataUpdateMessageComposer = 540; // AS3-verified (ghost fix): onItemDataUpdate
    public const int ItemRemoveMessageComposer = 2859;
    public const int ItemsMessageComposer = 3379;
    public const int ItemsStateUpdateMessageComposer = 1787; // AS3-verified (ghost fix): onItemsStateUpdate
    public const int ItemStateUpdateMessageComposer = 834; // AS3-verified (ghost fix): onItemStateUpdate
    public const int ItemUpdateMessageComposer = 1198;
    public const int ObjectAddMessageComposer = 368;
    public const int ObjectDataUpdateMessageComposer = 2329;
    public const int ObjectRemoveConfirmMessageComposer = 3643; // AS3-verified (ghost fix): onObjectRemoveConfirm
    public const int ObjectRemoveMessageComposer = 1916;

    public const int
        ObjectRemoveMultipleMessageComposer =
            9013; // UNRESOLVED: collided with DailyTasksTaskUpdateMessageComposer after the WIN63-202607011411 client header remap; ObjectRemoveMultipleMessageComposer has no ported client counterpart yet so its real header could not be verified - placeholder pending a proper revision retrace

    public const int ObjectsDataUpdateMessageComposer = 632;
    public const int ObjectsMessageComposer = 2104;
    public const int ObjectUpdateMessageComposer = 114;
    public const int RoomEntryInfoMessageComposer = 2914;

    public const int RoomPropertyMessageComposer = 1956; // AS3-verified: onRoomProperty (best of a weak field, reasonably confident)

    public const int RoomVisualizationSettingsComposer = 2986; // AS3-verified (ghost fix): onRoomVisualizationSettings @ RoomSessionManager
    public const int SlideObjectBundleMessageComposer = 2794;
    public const int SpecialRoomEffectMessageComposer = 536; // AS3-verified (ghost fix): onSpecialRoomEvent
    public const int UserChangeMessageComposer = 3798;
    public const int UserRemoveMessageComposer = 3693;
    public const int UsersMessageComposer = 996;
    public const int UserUpdateMessageComposer = 2613;
    public const int WiredMovementsMessageComposer = 325; // AS3-verified (ghost fix): onWiredMovements
    public const int CanCreateRoomComposer = 3592;
    public const int CanCreateRoomEventComposer = 1497;
    public const int CategoriesWithVisitorCountComposer = 704;
    public const int CompetitionRoomsDataMessageComposer = 84;
    public const int ConvertedRoomIdComposer = 3494;
    public const int DoorbellMessageComposer = 466;
    public const int FavouriteChangedComposer = 3081;
    public const int FavouritesComposer = 1055;
    public const int FlatAccessDeniedMessageComposer = 1086;
    public const int FlatCreatedComposer = 1712;
    public const int GetGuestRoomResultComposer = 3042;
    public const int GuestRoomSearchResultComposer = 1265;
    public const int NavigatorSettingsComposer = 3586;
    public const int OfficialRoomsComposer = 2211;
    public const int PopularRoomTagsResultComposer = 2952;
    public const int RoomEventCancelComposer = 894;
    public const int RoomEventComposer = 2481; // AS3-verified (ghost fix): onRoomEventEvent
    public const int RoomInfoUpdatedComposer = 3030;
    public const int RoomRatingComposer = 2502;
    public const int UserEventCatsComposer = 1370;
    public const int UserFlatCatsComposer = 837;
    public const int FurniListAddOrUpdateComposer = 3151;
    public const int FurniListComposer = 2694;
    public const int FurniListInvalidateComposer = 1856;
    public const int FurniListRemoveComposer = 1156;

    public const int PostItPlacedComposer = 2145; // AS3-verified: onPostItPlaced

    public const int OpenComposer = 2635; // AS3-verified (ghost fix): onOpen
    public const int WiredFurniActionComposer = 655;
    public const int WiredFurniAddonComposer = 1772;
    public const int WiredFurniConditionComposer = 2339;
    public const int WiredFurniSelectorComposer = 108;
    public const int WiredFurniTriggerComposer = 201;
    public const int WiredFurniVariableComposer = 1520;
    public const int WiredRewardResultMessageComposer = 955;
    public const int WiredSaveSuccessComposer = 1875;
    public const int WiredValidationErrorComposer = 1230; // AS3-verified (ghost fix): onWiredMenuError @ WiredMenuInspectionTab

    #endregion
}
