using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Vortex.Specs.Model;
using Vortex.Specs.Yaml;

namespace Vortex.Specs.Persistence;

public enum SpecWriteOutcome
{
    /// <summary>The file did not exist.</summary>
    Created,

    /// <summary>The generated block changed; hand-written blocks were carried across untouched.</summary>
    Updated,

    /// <summary>Byte-identical to what is already on disk. Nothing written.</summary>
    Unchanged,

    /// <summary>
    /// The generated block had been hand-edited. Nothing was overwritten; the new content was put
    /// beside it for a person to reconcile.
    /// </summary>
    Blocked,
}

public sealed record SpecWriteResult(string Path, SpecWriteOutcome Outcome, string? Detail = null);

/// <summary>
/// Reads and writes spec files, preserving everything a person has written into them.
/// </summary>
/// <remarks>
/// A spec file has three parts. <c>generated:</c> belongs to the tool and is replaced on every scan.
/// <c>verified:</c> and <c>manual:</c> belong to whoever is reading captures and arguing with the
/// evidence, and the tool never writes into them.
/// <para>
/// A digest of the generated block is stored with it, which turns "did anybody edit this?" into a
/// question with an answer. Where the answer is yes, the regeneration is written to a sibling file
/// and the original is left alone: a tool that silently reverts a correction somebody made by hand
/// teaches people not to make corrections.
/// </para>
/// </remarks>
public sealed class SpecStore(string root)
{
    private const string GeneratedKey = "generated";
    private const string VerifiedKey = "verified";
    private const string ManualKey = "manual";
    private const string DigestKey = "generated_digest";

    private static readonly string Header = string.Join(
        '\n',
        "Generated by `habbo-spec`. Do not hand-edit anything under `generated:` — it is replaced on",
        "every scan, and an edit there blocks the next regeneration instead of being silently lost.",
        "",
        "Write corrections under `verified:` (backed by evidence) or `manual:` (notes and context).",
        "Both are preserved verbatim across regenerations.",
        "",
        "Existing emulator behaviour is evidence, not authority.",
        "Reference emulator behaviour is evidence, not authority.",
        "Unknown official behaviour must remain explicitly unknown."
    );

    public string Root { get; } = root;

    public string PathFor(params string[] segments) => Path.Combine([Root, .. segments]);

    /// <summary>
    /// Writes one spec document, merging with what is already there.
    /// </summary>
    /// <param name="force">
    /// Replace the generated block even when it was hand-edited. Hand-written <c>verified:</c> and
    /// <c>manual:</c> blocks are still preserved — force overrides the safety net on the generated
    /// block only, never on somebody's own writing.
    /// </param>
    public SpecWriteResult Write(
        string path,
        string kind,
        YamlMapping generated,
        bool force = false
    )
    {
        string full = Path.IsPathRooted(path) ? path : Path.Combine(Root, path);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);

        YamlNode verified = YamlNode.Mapping();
        YamlNode manual = YamlNode.Mapping();
        bool exists = File.Exists(full);
        string? existingText = exists ? File.ReadAllText(full) : null;

        if (existingText is not null)
        {
            YamlMapping existing;

            try
            {
                existing = YamlReader.ReadMapping(existingText);
            }
            catch (YamlParseException error)
            {
                return new SpecWriteResult(
                    full,
                    SpecWriteOutcome.Blocked,
                    $"the file on disk is not readable as a spec ({error.Message}); it was left alone"
                );
            }

            verified = existing[VerifiedKey] ?? verified;
            manual = existing[ManualKey] ?? manual;

            YamlNode? existingGenerated = existing[GeneratedKey];
            string? storedDigest = existing.String(DigestKey);

            if (existingGenerated is not null && storedDigest is not null)
            {
                string actual = Digest(existingGenerated);

                if (!string.Equals(actual, storedDigest, StringComparison.Ordinal) && !force)
                {
                    string sidecar = full + ".regenerated.yaml";
                    File.WriteAllText(sidecar, Render(kind, generated, verified, manual));

                    return new SpecWriteResult(
                        full,
                        SpecWriteOutcome.Blocked,
                        "the generated block was edited by hand; the new version was written to "
                            + Path.GetFileName(sidecar)
                            + " instead of overwriting it"
                    );
                }
            }
        }

        string text = Render(kind, generated, verified, manual);

        if (existingText is not null && string.Equals(existingText, text, StringComparison.Ordinal))
        {
            return new SpecWriteResult(full, SpecWriteOutcome.Unchanged);
        }

        File.WriteAllText(full, text);

        return new SpecWriteResult(
            full,
            exists ? SpecWriteOutcome.Updated : SpecWriteOutcome.Created
        );
    }

    private static string Render(
        string kind,
        YamlMapping generated,
        YamlNode verified,
        YamlNode manual
    )
    {
        YamlMapping document = YamlNode
            .Mapping()
            .Set("spec", kind)
            .Set("spec_version", SpecConstants.SpecFormatVersion)
            .Set(DigestKey, Digest(generated))
            .Set(GeneratedKey, generated)
            .Set(VerifiedKey, verified)
            .Set(ManualKey, manual);

        return YamlWriter.Write(document, Header);
    }

    /// <summary>
    /// A digest of the generated block as it is rendered, not of the model behind it, so that
    /// reading a file back and re-digesting it gives the same answer.
    /// </summary>
    public static string Digest(YamlNode generated)
    {
        byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(YamlWriter.Write(generated)));
        StringBuilder builder = new(71);
        builder.Append("sha256:");

        foreach (byte value in hash)
        {
            builder.Append(value.ToString("x2", CultureInfo.InvariantCulture));
        }

        return builder.ToString();
    }

    public YamlMapping? Read(string path)
    {
        string full = Path.IsPathRooted(path) ? path : Path.Combine(Root, path);

        return File.Exists(full) ? YamlReader.ReadMapping(File.ReadAllText(full)) : null;
    }

    /// <summary>Every spec file under the output root, in a stable order.</summary>
    public IReadOnlyList<string> Enumerate()
    {
        if (!Directory.Exists(Root))
        {
            return [];
        }

        List<string> files =
        [
            .. Directory.EnumerateFiles(Root, "*.yaml", SearchOption.AllDirectories),
        ];
        files.Sort(StringComparer.Ordinal);

        return files;
    }

    /// <summary>
    /// Writes the plain-text file that is not a spec: the run report. Left outside the merge
    /// machinery because it is a snapshot of one run and carries nothing worth preserving.
    /// </summary>
    public void WriteText(string path, string content)
    {
        string full = Path.IsPathRooted(path) ? path : Path.Combine(Root, path);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    /// <summary>A file-system-safe name for a symbolic packet or feature id.</summary>
    public static string FileName(string name)
    {
        StringBuilder builder = new(name.Length);

        foreach (char c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) || c is '-' or '_' or '.' ? c : '_');
        }

        string safe = builder.ToString();

        return safe.Length == 0 ? "unnamed" : safe;
    }
}
