using System.Collections.Generic;
using FluentAssertions;
using Vortex.Specs.Yaml;
using Xunit;

namespace Vortex.Specs.Tests.Yaml;

public class YamlRoundTripTests
{
    private static YamlMapping SampleDocument()
    {
        YamlMapping field = YamlNode
            .Mapping()
            .Set("index", 0)
            .Set("name", "item_id")
            .Set("type", "int32")
            .Set(
                "evidence",
                YamlNode.Sequence([YamlNode.Scalar("ev_aabbcc"), YamlNode.Scalar("ev_ddeeff")])
            );

        YamlMapping unnamed = YamlNode
            .Mapping()
            .Set("index", 1)
            .Set("name", "unknown_1")
            .Set("type", "int32")
            .Set("note", "the client reads it but never uses it: no name available")
            .Set("evidence", YamlNode.Sequence());

        return YamlNode
            .Mapping()
            .Set("spec", "packet")
            .Set("spec_version", 1)
            .Set("name", "MoveObject")
            .Set("direction", "incoming")
            .Set("mapped_in_vortex", true)
            .Set("fields", YamlNode.Sequence([field, unnamed]))
            .Set("verified", YamlNode.Mapping())
            .Set("manual", YamlNode.Mapping().Set("owner", "ctuto"));
    }

    [Fact]
    public void Writes_then_reads_back_the_same_tree()
    {
        string text = YamlWriter.Write(SampleDocument());
        YamlMapping read = YamlReader.ReadMapping(text);

        read.String("spec").Should().Be("packet");
        read.Int("spec_version").Should().Be(1);
        read.String("name").Should().Be("MoveObject");
        read.Bool("mapped_in_vortex").Should().BeTrue();

        YamlSequence fields = read.SequenceAt("fields")!;
        fields.Items.Should().HaveCount(2);

        YamlMapping first = (YamlMapping)fields.Items[0];
        first.Int("index").Should().Be(0);
        first.String("name").Should().Be("item_id");
        first.SequenceAt("evidence")!.Items.Should().HaveCount(2);

        YamlMapping second = (YamlMapping)fields.Items[1];
        second.String("name").Should().Be("unknown_1");
        second.String("note").Should().Contain("no name available");
        second.SequenceAt("evidence")!.Items.Should().BeEmpty();

        read.Mapping("verified")!.Entries.Should().BeEmpty();
        read.Mapping("manual")!.String("owner").Should().Be("ctuto");
    }

    [Fact]
    public void Emission_is_byte_stable_across_writes()
    {
        string first = YamlWriter.Write(SampleDocument());
        string second = YamlWriter.Write(SampleDocument());

        second.Should().Be(first);
    }

    [Fact]
    public void Reparsing_and_rewriting_produces_identical_text()
    {
        string first = YamlWriter.Write(SampleDocument());
        string second = YamlWriter.Write(YamlReader.Read(first));

        second.Should().Be(first);
    }

    [Theory]
    [InlineData("true")]
    [InlineData("false")]
    [InlineData("null")]
    [InlineData("no")]
    [InlineData("12")]
    [InlineData("1.5")]
    [InlineData("- leading dash")]
    [InlineData("has: a colon")]
    [InlineData("trailing space ")]
    [InlineData("")]
    [InlineData("quote \" and backslash \\")]
    [InlineData("hash # inside")]
    public void String_scalars_survive_a_round_trip_verbatim(string value)
    {
        YamlMapping document = YamlNode.Mapping().Set("value", value);

        string text = YamlWriter.Write(document);
        YamlMapping read = YamlReader.ReadMapping(text);

        read.String("value").Should().Be(value);
    }

    [Fact]
    public void Comments_and_document_markers_are_ignored()
    {
        const string text = """
            # generated by habbo-spec
            ---
            name: MoveObject   # the symbolic name, never the header id
            fields:
              - index: 0
                name: item_id
            """;

        YamlMapping read = YamlReader.ReadMapping(text);

        read.String("name").Should().Be("MoveObject");
        ((YamlMapping)read.SequenceAt("fields")!.Items[0]).String("name").Should().Be("item_id");
    }

    [Fact]
    public void Hand_written_flow_collections_are_accepted()
    {
        const string text = """
            packets: [RoomReady, FloorHeightMap]
            given: { has_rights: false, in_room: true }
            empty_list: []
            empty_map: {}
            """;

        YamlMapping read = YamlReader.ReadMapping(text);

        read.SequenceAt("packets")!.Items.Should().HaveCount(2);
        read.Mapping("given")!.String("has_rights").Should().Be("false");
        read.SequenceAt("empty_list")!.Items.Should().BeEmpty();
        read.Mapping("empty_map")!.Entries.Should().BeEmpty();
    }

    [Fact]
    public void Nested_sequences_of_mappings_round_trip()
    {
        YamlMapping document = YamlNode
            .Mapping()
            .Set(
                "positions",
                YamlNode.Sequence([
                    YamlNode
                        .Mapping()
                        .Set("origin", "vortex")
                        .Set("emitted", YamlNode.Sequence([YamlNode.Scalar("ObjectUpdate")])),
                    YamlNode
                        .Mapping()
                        .Set("origin", "arcturus")
                        .Set(
                            "emitted",
                            YamlNode.Sequence([
                                YamlNode.Scalar("NotificationDialog"),
                                YamlNode.Scalar("ObjectUpdate"),
                            ])
                        ),
                ])
            );

        YamlMapping read = YamlReader.ReadMapping(YamlWriter.Write(document));
        YamlSequence positions = read.SequenceAt("positions")!;

        positions.Items.Should().HaveCount(2);
        ((YamlMapping)positions.Items[1]).SequenceAt("emitted")!.Items.Should().HaveCount(2);
    }

    [Fact]
    public void Tabs_for_indentation_are_rejected_with_a_line_number()
    {
        YamlParseException error = Assert.Throws<YamlParseException>(() =>
            YamlReader.Read("name: x\n\tvalue: 1\n")
        );

        error.Line.Should().Be(2);
    }

    [Fact]
    public void Anchors_are_rejected_rather_than_silently_dropped()
    {
        Assert.Throws<YamlParseException>(() => YamlReader.Read("base: &anchor\n  a: 1\n"));
    }

    [Fact]
    public void A_header_comment_is_emitted_above_the_body()
    {
        string text = YamlWriter.Write(
            YamlNode.Mapping().Set("name", "MoveObject"),
            "generated by habbo-spec\ndo not hand-edit the generated block"
        );

        text.Should().StartWith("# generated by habbo-spec\n# do not hand-edit");
        YamlReader.ReadMapping(text).String("name").Should().Be("MoveObject");
    }

    [Fact]
    public void Dictionary_backed_mappings_keep_insertion_order()
    {
        YamlMapping mapping = YamlNode.Mapping();

        foreach (
            KeyValuePair<string, string> pair in new[]
            {
                new KeyValuePair<string, string>("zulu", "1"),
                new KeyValuePair<string, string>("alpha", "2"),
                new KeyValuePair<string, string>("mike", "3"),
            }
        )
        {
            mapping.Set(pair.Key, pair.Value);
        }

        YamlWriter.Write(mapping).Should().Be("zulu: \"1\"\nalpha: \"2\"\nmike: \"3\"\n");
    }
}
