// Wire-level int values for Vortex.Primitives.Furniture.Enums.ProductType /
// Vortex.Primitives.Rooms.Enums.FurnitureUsageType / Vortex.Primitives.Furniture.StuffData.StuffDataType
// and the FurnitureCategory column on furniture_definitions. Kept as plain int values (not strings)
// because the dashboard API deserializes enums as numbers (System.Text.Json default), matching how
// CreateCatalogProductRequest.ProductType etc. are already sent elsewhere.

export const PRODUCT_TYPES = [
  { value: 0, label: 'Floor' },
  { value: 1, label: 'Wall' },
  { value: 2, label: 'Effect' },
  { value: 3, label: 'Badge' },
  { value: 4, label: 'Robot' },
  { value: 5, label: 'HabboClub' },
  { value: 6, label: 'Pet' },
];

export const FURNITURE_CATEGORIES = [
  { value: 1, label: 'Default' },
  { value: 2, label: 'Wall paper' },
  { value: 3, label: 'Floor' },
  { value: 4, label: 'Landscape' },
  { value: 5, label: 'Post it' },
  { value: 6, label: 'Poster' },
  { value: 7, label: 'Sound set' },
  { value: 8, label: 'Trax song' },
  { value: 9, label: 'Present' },
  { value: 10, label: 'Ecotron box' },
  { value: 11, label: 'Trophy' },
  { value: 12, label: 'Credit furni' },
  { value: 13, label: 'Pet shampoo' },
  { value: 14, label: 'Pet custom part' },
  { value: 15, label: 'Pet custom part shampoo' },
  { value: 16, label: 'Pet saddle' },
  { value: 17, label: 'Guild furni' },
  { value: 18, label: 'Game furni' },
  { value: 19, label: 'Monsterplant seed' },
  { value: 20, label: 'Monsterplant revival' },
  { value: 21, label: 'Monsterplant rebreed' },
  { value: 22, label: 'Monsterplant fertilize' },
  { value: 23, label: 'Figure purchasable set' },
];

export const USAGE_POLICIES = [
  { value: 0, label: 'Nobody' },
  { value: 1, label: 'Controller' },
  { value: 2, label: 'Everybody' },
];

// The real, complete set of registered furniture "logic" keys -- there is no enum for this column
// (it's a free string matched at runtime against every [RoomObjectLogic("...")]-attributed class
// found by assembly scanning, see RoomObjectLogicFeatureProcessor/RoomObjectLogicProvider). Typing
// one from memory means guessing; this list is grepped directly from those attributes so every
// value here is guaranteed to resolve to a real behavior instead of silently falling back to
// default_floor at runtime. Wired trigger/condition/action/selector/extra/variable pieces are
// shown with their raw internal key (not relabeled) since that's what every other catalog tool
// references them by too.
export const LOGIC_GROUPS = [
  {
    label: 'Basic',
    options: [
      { value: 'default_avatar', label: 'default_avatar - Default (avatar)' },
      { value: 'default_floor', label: 'default_floor - Default (floor item)' },
      { value: 'default_wall', label: 'default_wall - Default (wall item)' },
      { value: 'dice', label: 'dice - Dice' },
      { value: 'fireworks', label: 'fireworks - Fireworks' },
      { value: 'gate', label: 'gate - Gate (blocks/unblocks a tile)' },
      { value: 'nest', label: 'nest' },
      { value: 'petdrink', label: 'petdrink' },
      { value: 'roller', label: 'roller - Roller (conveyor belt)' },
      { value: 'room_invisible_click_tile', label: 'room_invisible_click_tile - Invisible click tile' },
      { value: 'vending', label: 'vending' },
      { value: 'vendingmachine', label: 'vendingmachine' },
      { value: 'vendingmachine_no_sides', label: 'vendingmachine_no_sides' },
    ],
  },
  {
    label: 'Furniture',
    options: [
      { value: 'furniture_background_color', label: 'furniture_background_color' },
      { value: 'furniture_basic', label: 'furniture_basic' },
      { value: 'furniture_clothing_change', label: 'furniture_clothing_change' },
      { value: 'furniture_coinschest', label: 'furniture_coinschest' },
      { value: 'furniture_crackable', label: 'furniture_crackable' },
      { value: 'furniture_custom_stack_height', label: 'furniture_custom_stack_height' },
      { value: 'furniture_dice', label: 'furniture_dice' },
      { value: 'furniture_ecotron_box', label: 'furniture_ecotron_box' },
      { value: 'furniture_effectbox', label: 'furniture_effectbox' },
      { value: 'furniture_fireworks', label: 'furniture_fireworks' },
      { value: 'furniture_furnichest', label: 'furniture_furnichest' },
      { value: 'furniture_group_forum_terminal', label: 'furniture_group_forum_terminal' },
      { value: 'furniture_guild_customized', label: 'furniture_guild_customized' },
      { value: 'furniture_guild_gate', label: 'furniture_guild_gate' },
      { value: 'furniture_habbowheel', label: 'furniture_habbowheel' },
      { value: 'furniture_hockey_score', label: 'furniture_hockey_score' },
      { value: 'furniture_monsterplant_seed', label: 'furniture_monsterplant_seed' },
      { value: 'furniture_muItistate', label: 'furniture_muItistate' },
      { value: 'furniture_multistate', label: 'furniture_multistate' },
      { value: 'furniture_mysterybox', label: 'furniture_mysterybox' },
      { value: 'furniture_mysterytrophy', label: 'furniture_mysterytrophy' },
      { value: 'furniture_nft_reward_box', label: 'furniture_nft_reward_box' },
      { value: 'furniture_one_way_door', label: 'furniture_one_way_door' },
      { value: 'furniture_present', label: 'furniture_present' },
      { value: 'furniture_purchasable_clothing', label: 'furniture_purchasable_clothing' },
      { value: 'furniture_pushable', label: 'furniture_pushable' },
      { value: 'furniture_roomdimmer', label: 'furniture_roomdimmer' },
      { value: 'furniture_score', label: 'furniture_score' },
      { value: 'furniture_static', label: 'furniture_static' },
      { value: 'furniture_welcome_gift', label: 'furniture_welcome_gift' },
    ],
  },
  {
    label: 'Pets',
    options: [
      { value: 'monsterplant_seed', label: 'monsterplant_seed - Monsterplant seed' },
      { value: 'pet_drink', label: 'pet_drink - Pet drink bowl' },
      { value: 'pet_food', label: 'pet_food - Pet food bowl' },
      { value: 'pet_nest', label: 'pet_nest - Pet nest' },
      { value: 'pet_toy', label: 'pet_toy' },
      { value: 'pet_trampoline', label: 'pet_trampoline' },
    ],
  },
  {
    label: 'Games: Battle Banzai',
    options: [
      { value: 'battlebanzai_gate_blue', label: 'battlebanzai_gate_blue' },
      { value: 'battlebanzai_gate_green', label: 'battlebanzai_gate_green' },
      { value: 'battlebanzai_gate_red', label: 'battlebanzai_gate_red' },
      { value: 'battlebanzai_gate_yellow', label: 'battlebanzai_gate_yellow' },
      { value: 'battlebanzai_random_teleport', label: 'battlebanzai_random_teleport' },
      { value: 'battlebanzai_random_teleport_exclude', label: 'battlebanzai_random_teleport_exclude' },
      { value: 'battlebanzai_tile', label: 'battlebanzai_tile' },
    ],
  },
  {
    label: 'Games: Freeze',
    options: [
      { value: 'freeze_block', label: 'freeze_block' },
      { value: 'freeze_counter_blue', label: 'freeze_counter_blue' },
      { value: 'freeze_counter_green', label: 'freeze_counter_green' },
      { value: 'freeze_counter_red', label: 'freeze_counter_red' },
      { value: 'freeze_counter_yellow', label: 'freeze_counter_yellow' },
      { value: 'freeze_exit', label: 'freeze_exit' },
      { value: 'freeze_gate_blue', label: 'freeze_gate_blue' },
      { value: 'freeze_gate_green', label: 'freeze_gate_green' },
      { value: 'freeze_gate_red', label: 'freeze_gate_red' },
      { value: 'freeze_gate_yellow', label: 'freeze_gate_yellow' },
      { value: 'freeze_tile', label: 'freeze_tile' },
    ],
  },
  {
    label: 'Games: Football',
    options: [
      { value: 'football_goal_blue', label: 'football_goal_blue' },
      { value: 'football_goal_green', label: 'football_goal_green' },
      { value: 'football_goal_red', label: 'football_goal_red' },
      { value: 'football_goal_yellow', label: 'football_goal_yellow' },
    ],
  },
  {
    label: 'Games: other',
    options: [
      { value: 'game_timer', label: 'game_timer' },
    ],
  },
  {
    label: 'Wired: Triggers',
    options: [
      { value: 'wf_trg_at_given_time', label: 'wf_trg_at_given_time' },
      { value: 'wf_trg_at_time_long', label: 'wf_trg_at_time_long' },
      { value: 'wf_trg_bot_reached_avtr', label: 'wf_trg_bot_reached_avtr' },
      { value: 'wf_trg_bot_reached_stf', label: 'wf_trg_bot_reached_stf' },
      { value: 'wf_trg_click_furni', label: 'wf_trg_click_furni' },
      { value: 'wf_trg_click_tile', label: 'wf_trg_click_tile' },
      { value: 'wf_trg_click_user', label: 'wf_trg_click_user' },
      { value: 'wf_trg_clock_counter', label: 'wf_trg_clock_counter' },
      { value: 'wf_trg_collision', label: 'wf_trg_collision' },
      { value: 'wf_trg_enter_room', label: 'wf_trg_enter_room' },
      { value: 'wf_trg_game_ends', label: 'wf_trg_game_ends' },
      { value: 'wf_trg_game_starts', label: 'wf_trg_game_starts' },
      { value: 'wf_trg_leave_room', label: 'wf_trg_leave_room' },
      { value: 'wf_trg_period_long', label: 'wf_trg_period_long' },
      { value: 'wf_trg_period_short', label: 'wf_trg_period_short' },
      { value: 'wf_trg_periodically', label: 'wf_trg_periodically' },
      { value: 'wf_trg_recv_signal', label: 'wf_trg_recv_signal' },
      { value: 'wf_trg_says_something', label: 'wf_trg_says_something' },
      { value: 'wf_trg_score_achieved', label: 'wf_trg_score_achieved' },
      { value: 'wf_trg_state_changed', label: 'wf_trg_state_changed' },
      { value: 'wf_trg_stuff_state', label: 'wf_trg_stuff_state' },
      { value: 'wf_trg_transaction_complete', label: 'wf_trg_transaction_complete' },
      { value: 'wf_trg_transaction_fail', label: 'wf_trg_transaction_fail' },
      { value: 'wf_trg_user_exits_room', label: 'wf_trg_user_exits_room' },
      { value: 'wf_trg_user_performs_action', label: 'wf_trg_user_performs_action' },
      { value: 'wf_trg_var_changed', label: 'wf_trg_var_changed' },
      { value: 'wf_trg_walks_off_furni', label: 'wf_trg_walks_off_furni' },
      { value: 'wf_trg_walks_on_furni', label: 'wf_trg_walks_on_furni' },
    ],
  },
  {
    label: 'Wired: Conditions',
    options: [
      { value: 'wf_cnd_actor_dir', label: 'wf_cnd_actor_dir' },
      { value: 'wf_cnd_actor_in_group', label: 'wf_cnd_actor_in_group' },
      { value: 'wf_cnd_actor_in_team', label: 'wf_cnd_actor_in_team' },
      { value: 'wf_cnd_counter_time_matches', label: 'wf_cnd_counter_time_matches' },
      { value: 'wf_cnd_date_rng_active', label: 'wf_cnd_date_rng_active' },
      { value: 'wf_cnd_furnis_hv_avtrs', label: 'wf_cnd_furnis_hv_avtrs' },
      { value: 'wf_cnd_habbo_owns_badge', label: 'wf_cnd_habbo_owns_badge' },
      { value: 'wf_cnd_has_altitude', label: 'wf_cnd_has_altitude' },
      { value: 'wf_cnd_has_furni_on', label: 'wf_cnd_has_furni_on' },
      { value: 'wf_cnd_has_handitem', label: 'wf_cnd_has_handitem' },
      { value: 'wf_cnd_has_same_height', label: 'wf_cnd_has_same_height' },
      { value: 'wf_cnd_has_var', label: 'wf_cnd_has_var' },
      { value: 'wf_cnd_match_date', label: 'wf_cnd_match_date' },
      { value: 'wf_cnd_match_snapshot_new', label: 'wf_cnd_match_snapshot_new' },
      { value: 'wf_cnd_match_time', label: 'wf_cnd_match_time' },
      { value: 'wf_cnd_neg_has_var', label: 'wf_cnd_neg_has_var' },
      { value: 'wf_cnd_not_actor_in_group', label: 'wf_cnd_not_actor_in_group' },
      { value: 'wf_cnd_not_furni_on', label: 'wf_cnd_not_furni_on' },
      { value: 'wf_cnd_not_habbo_owns_badge', label: 'wf_cnd_not_habbo_owns_badge' },
      { value: 'wf_cnd_not_has_handitem', label: 'wf_cnd_not_has_handitem' },
      { value: 'wf_cnd_not_hv_avtrs', label: 'wf_cnd_not_hv_avtrs' },
      { value: 'wf_cnd_not_in_group', label: 'wf_cnd_not_in_group' },
      { value: 'wf_cnd_not_in_team', label: 'wf_cnd_not_in_team' },
      { value: 'wf_cnd_not_match_snap_new', label: 'wf_cnd_not_match_snap_new' },
      { value: 'wf_cnd_not_stuff_is', label: 'wf_cnd_not_stuff_is' },
      { value: 'wf_cnd_not_trggrer_on', label: 'wf_cnd_not_trggrer_on' },
      { value: 'wf_cnd_not_triggerer_match', label: 'wf_cnd_not_triggerer_match' },
      { value: 'wf_cnd_not_user_count', label: 'wf_cnd_not_user_count' },
      { value: 'wf_cnd_not_user_performs_action', label: 'wf_cnd_not_user_performs_action' },
      { value: 'wf_cnd_not_wearing_b', label: 'wf_cnd_not_wearing_b' },
      { value: 'wf_cnd_not_wearing_fx', label: 'wf_cnd_not_wearing_fx' },
      { value: 'wf_cnd_not_wears_effect', label: 'wf_cnd_not_wears_effect' },
      { value: 'wf_cnd_not_wears_handitem', label: 'wf_cnd_not_wears_handitem' },
      { value: 'wf_cnd_slc_quantity', label: 'wf_cnd_slc_quantity' },
      { value: 'wf_cnd_stuff_is', label: 'wf_cnd_stuff_is' },
      { value: 'wf_cnd_team_has_rank', label: 'wf_cnd_team_has_rank' },
      { value: 'wf_cnd_team_has_score', label: 'wf_cnd_team_has_score' },
      { value: 'wf_cnd_time_less_than', label: 'wf_cnd_time_less_than' },
      { value: 'wf_cnd_time_more_than', label: 'wf_cnd_time_more_than' },
      { value: 'wf_cnd_trggrer_on_frn', label: 'wf_cnd_trggrer_on_frn' },
      { value: 'wf_cnd_triggerer_match', label: 'wf_cnd_triggerer_match' },
      { value: 'wf_cnd_user_count_in', label: 'wf_cnd_user_count_in' },
      { value: 'wf_cnd_user_performs_action', label: 'wf_cnd_user_performs_action' },
      { value: 'wf_cnd_var_age_match', label: 'wf_cnd_var_age_match' },
      { value: 'wf_cnd_var_val_match', label: 'wf_cnd_var_val_match' },
      { value: 'wf_cnd_wearing_effect', label: 'wf_cnd_wearing_effect' },
      { value: 'wf_cnd_wears_effect', label: 'wf_cnd_wears_effect' },
      { value: 'wf_cnd_wears_handitem', label: 'wf_cnd_wears_handitem' },
    ],
  },
  {
    label: 'Wired: Actions',
    options: [
      { value: 'wf_act_adjust_clock', label: 'wf_act_adjust_clock' },
      { value: 'wf_act_bot_clothes', label: 'wf_act_bot_clothes' },
      { value: 'wf_act_bot_follow_avatar', label: 'wf_act_bot_follow_avatar' },
      { value: 'wf_act_bot_give_handitem', label: 'wf_act_bot_give_handitem' },
      { value: 'wf_act_bot_move', label: 'wf_act_bot_move' },
      { value: 'wf_act_bot_talk', label: 'wf_act_bot_talk' },
      { value: 'wf_act_bot_talk_to_avatar', label: 'wf_act_bot_talk_to_avatar' },
      { value: 'wf_act_bot_teleport', label: 'wf_act_bot_teleport' },
      { value: 'wf_act_call_stacks', label: 'wf_act_call_stacks' },
      { value: 'wf_act_cancel_transaction', label: 'wf_act_cancel_transaction' },
      { value: 'wf_act_change_var_val', label: 'wf_act_change_var_val' },
      { value: 'wf_act_chase', label: 'wf_act_chase' },
      { value: 'wf_act_cnd_furni_to_furni', label: 'wf_act_cnd_furni_to_furni' },
      { value: 'wf_act_cnd_move_furni', label: 'wf_act_cnd_move_furni' },
      { value: 'wf_act_control_clock', label: 'wf_act_control_clock' },
      { value: 'wf_act_flee', label: 'wf_act_flee' },
      { value: 'wf_act_forward_user', label: 'wf_act_forward_user' },
      { value: 'wf_act_freeze_habbo', label: 'wf_act_freeze_habbo' },
      { value: 'wf_act_furni_to_user', label: 'wf_act_furni_to_user' },
      { value: 'wf_act_give_currency', label: 'wf_act_give_currency' },
      { value: 'wf_act_give_effect', label: 'wf_act_give_effect' },
      { value: 'wf_act_give_furni', label: 'wf_act_give_furni' },
      { value: 'wf_act_give_score', label: 'wf_act_give_score' },
      { value: 'wf_act_give_score_tm', label: 'wf_act_give_score_tm' },
      { value: 'wf_act_give_var', label: 'wf_act_give_var' },
      { value: 'wf_act_init_transaction', label: 'wf_act_init_transaction' },
      { value: 'wf_act_join_team', label: 'wf_act_join_team' },
      { value: 'wf_act_kick_user', label: 'wf_act_kick_user' },
      { value: 'wf_act_leave_team', label: 'wf_act_leave_team' },
      { value: 'wf_act_lower_furni', label: 'wf_act_lower_furni' },
      { value: 'wf_act_move_furni_to', label: 'wf_act_move_furni_to' },
      { value: 'wf_act_move_rotate', label: 'wf_act_move_rotate' },
      { value: 'wf_act_move_to_dir', label: 'wf_act_move_to_dir' },
      { value: 'wf_act_mute_triggerer', label: 'wf_act_mute_triggerer' },
      { value: 'wf_act_neg_call_stacks', label: 'wf_act_neg_call_stacks' },
      { value: 'wf_act_neg_send_signal', label: 'wf_act_neg_send_signal' },
      { value: 'wf_act_raise_furni', label: 'wf_act_raise_furni' },
      { value: 'wf_act_rel_mov', label: 'wf_act_rel_mov' },
      { value: 'wf_act_remove_var', label: 'wf_act_remove_var' },
      { value: 'wf_act_reset_timers', label: 'wf_act_reset_timers' },
      { value: 'wf_act_send_signal', label: 'wf_act_send_signal' },
      { value: 'wf_act_set_altitude', label: 'wf_act_set_altitude' },
      { value: 'wf_act_show_message', label: 'wf_act_show_message' },
      { value: 'wf_act_show_message_room', label: 'wf_act_show_message_room' },
      { value: 'wf_act_teleport_to', label: 'wf_act_teleport_to' },
      { value: 'wf_act_toggle_state', label: 'wf_act_toggle_state' },
      { value: 'wf_act_toggle_to_rnd', label: 'wf_act_toggle_to_rnd' },
      { value: 'wf_act_tp_furni_to_habbo', label: 'wf_act_tp_furni_to_habbo' },
      { value: 'wf_act_unfreeze_habbo', label: 'wf_act_unfreeze_habbo' },
    ],
  },
  {
    label: 'Wired: Selectors',
    options: [
      { value: 'wf_slc_furni_altitude', label: 'wf_slc_furni_altitude' },
      { value: 'wf_slc_furni_area', label: 'wf_slc_furni_area' },
      { value: 'wf_slc_furni_bytype', label: 'wf_slc_furni_bytype' },
      { value: 'wf_slc_furni_neighborhood', label: 'wf_slc_furni_neighborhood' },
      { value: 'wf_slc_furni_onfurni', label: 'wf_slc_furni_onfurni' },
      { value: 'wf_slc_furni_picks', label: 'wf_slc_furni_picks' },
      { value: 'wf_slc_furni_signal', label: 'wf_slc_furni_signal' },
      { value: 'wf_slc_furni_with_var', label: 'wf_slc_furni_with_var' },
      { value: 'wf_slc_remote', label: 'wf_slc_remote' },
      { value: 'wf_slc_users_area', label: 'wf_slc_users_area' },
      { value: 'wf_slc_users_byaction', label: 'wf_slc_users_byaction' },
      { value: 'wf_slc_users_byname', label: 'wf_slc_users_byname' },
      { value: 'wf_slc_users_bytype', label: 'wf_slc_users_bytype' },
      { value: 'wf_slc_users_group', label: 'wf_slc_users_group' },
      { value: 'wf_slc_users_handitem', label: 'wf_slc_users_handitem' },
      { value: 'wf_slc_users_neighborhood', label: 'wf_slc_users_neighborhood' },
      { value: 'wf_slc_users_onfurni', label: 'wf_slc_users_onfurni' },
      { value: 'wf_slc_users_signal', label: 'wf_slc_users_signal' },
      { value: 'wf_slc_users_team', label: 'wf_slc_users_team' },
      { value: 'wf_slc_users_with_var', label: 'wf_slc_users_with_var' },
    ],
  },
  {
    label: 'Wired: Extras',
    options: [
      { value: 'wf_xtra_anim_time', label: 'wf_xtra_anim_time' },
      { value: 'wf_xtra_custom_contract', label: 'wf_xtra_custom_contract' },
      { value: 'wf_xtra_execution_limit', label: 'wf_xtra_execution_limit' },
      { value: 'wf_xtra_filter_furni', label: 'wf_xtra_filter_furni' },
      { value: 'wf_xtra_filter_furni_by_var', label: 'wf_xtra_filter_furni_by_var' },
      { value: 'wf_xtra_filter_users', label: 'wf_xtra_filter_users' },
      { value: 'wf_xtra_filter_users_by_var', label: 'wf_xtra_filter_users_by_var' },
      { value: 'wf_xtra_mov_carry_users', label: 'wf_xtra_mov_carry_users' },
      { value: 'wf_xtra_mov_no_animation', label: 'wf_xtra_mov_no_animation' },
      { value: 'wf_xtra_mov_physics', label: 'wf_xtra_mov_physics' },
      { value: 'wf_xtra_one_condition', label: 'wf_xtra_one_condition' },
      { value: 'wf_xtra_or_eval', label: 'wf_xtra_or_eval' },
      { value: 'wf_xtra_random', label: 'wf_xtra_random' },
      { value: 'wf_xtra_text_output_furni_name', label: 'wf_xtra_text_output_furni_name' },
      { value: 'wf_xtra_text_output_username', label: 'wf_xtra_text_output_username' },
      { value: 'wf_xtra_text_output_variable', label: 'wf_xtra_text_output_variable' },
      { value: 'wf_xtra_unseen', label: 'wf_xtra_unseen' },
    ],
  },
  {
    label: 'Wired: Variables',
    options: [
      { value: 'wf_var_context', label: 'wf_var_context' },
      { value: 'wf_var_furni', label: 'wf_var_furni' },
      { value: 'wf_var_quest', label: 'wf_var_quest' },
      { value: 'wf_var_quest_chain', label: 'wf_var_quest_chain' },
      { value: 'wf_var_reference', label: 'wf_var_reference' },
      { value: 'wf_var_room', label: 'wf_var_room' },
      { value: 'wf_var_user', label: 'wf_var_user' },
    ],
  },
  {
    label: 'Wired: other',
    options: [
      { value: 'wf_...', label: 'wf_...' },
      { value: 'wf_contract_payment', label: 'wf_contract_payment' },
      { value: 'wf_contract_reward', label: 'wf_contract_reward' },
      { value: 'wf_contract_trade', label: 'wf_contract_trade' },
      { value: 'wf_highscore', label: 'wf_highscore' },
    ],
  },
];

export const STUFF_DATA_TYPES = [
  { value: 0, label: 'Legacy key' },
  { value: 1, label: 'Map key' },
  { value: 2, label: 'String key' },
  { value: 3, label: 'Vote key' },
  { value: 4, label: 'Empty key' },
  { value: 5, label: 'Number key' },
  { value: 6, label: 'Highscore key' },
  { value: 7, label: 'Crackable key' },
];
