-- Pet vocals, lifted verbatim from the client's own text bundle
-- (external_flash_texts.txt, keys pet.vocals.<type>.<vocal>.<index>).
--
-- Nothing in the client resolves these keys, so the server picks a line and sends it as ordinary
-- room chat from the pet. Only types 15 and 35 ship lines; a pet of any other type stays quiet
-- rather than being given invented dialogue.
--
-- Apostrophes are doubled, not backslash-escaped: the lines are full of them ("I'm", "world's")
-- and backslash escaping breaks under NO_BACKSLASH_ESCAPES.
--
-- Re-running is harmless: the delete scopes to the rows this file owns.

DELETE FROM pet_vocals WHERE pet_type IN (15, 35);

INSERT INTO pet_vocals (pet_type, vocal_type, text) VALUES
    (15, 'DISOBEY', 'Nay. (Geddit?)'),
    (15, 'DISOBEY', 'I wish I could do as you ask, but I cannot.'),
    (15, 'DISOBEY', 'Leave me alone.'),
    (15, 'DRINKING', 'Ah, that''s the good stuff.'),
    (15, 'EATING', 'This is delicious!'),
    (15, 'GENERIC_HAPPY', '*Happu*'),
    (15, 'GENERIC_HAPPY', ':)'),
    (15, 'GENERIC_HAPPY', 'I think I''m happy, but it could be gas.'),
    (15, 'GENERIC_NEUTRAL', 'How are you today?'),
    (15, 'GENERIC_NEUTRAL', 'Hello!'),
    (15, 'GENERIC_NEUTRAL', 'Bah....'),
    (15, 'GENERIC_SAD', '*Sad*'),
    (15, 'GENERIC_SAD', 'I don''t feel myself today :('),
    (15, 'GREET_OWNER', 'Fantastic to see you today!'),
    (15, 'GREET_OWNER', 'Hello!'),
    (15, 'HUNGRY', 'I''m starving!'),
    (15, 'LEVEL_UP', 'I just leveled up!'),
    (15, 'MUTED', '*silencio*'),
    (15, 'PLAYFUL', 'Let''s do something fun today, like staring at a wall.'),
    (15, 'PLAYFUL', 'So bored.'),
    (15, 'PLAYING', 'Hey, let''s go for a ride!'),
    (15, 'SLEEPING', 'Zzzz.... Marston!'),
    (15, 'SLEEPING', 'Zzzz... Old Dan Tucker....'),
    (15, 'SLEEPING', 'Zzzz... I have a heart that can never be tamed...'),
    (15, 'THIRSTY', 'I''m thirsty!'),
    (15, 'TIRED', 'I''m so tired!'),
    (15, 'UNKNOWN_COMMAND', 'I''m sorry, I don''t understand!'),
    (15, 'UNKNOWN_COMMAND', 'Whatever, speak English if you want me to do something.'),
    (35, 'DISOBEY', 'Well, I could do that. BUT, I just don''t feel like it.'),
    (35, 'DISOBEY', 'You''re repeating yourself.'),
    (35, 'DISOBEY', 'To do that would compromise my basic morals. Sorry, but no.'),
    (35, 'DRINKING', 'Drinking water after an entire day eating grass is simply heavenly.'),
    (35, 'DRINKING', '*Gulp* ..if it wasn''t for water.. *Gulp* ..life wouldn''t exist on this planet..'),
    (35, 'EATING', 'Veganism isn''t just for Christmas. Veganism is for life.'),
    (35, 'EATING', '*Crunch* I just ADORE meal times. *Crunch*'),
    (35, 'EATING', 'Mmmm. Healthy. *Crunch*'),
    (35, 'GENERIC_HAPPY', 'Today is a good day. Today is great.'),
    (35, 'GENERIC_HAPPY', 'With all the world''s chaos, it takes effort to see the good. Remember that it''s possible!'),
    (35, 'GENERIC_HAPPY', 'I''m glad I took that yoga class this morning: I''m feeling great right now.'),
    (35, 'GENERIC_NEUTRAL', 'There is always some madness in love. But there is also always some reason in madness.'),
    (35, 'GENERIC_NEUTRAL', 'Cows need love too.'),
    (35, 'GENERIC_NEUTRAL', 'New York? London? Paris? Tokyo? Give me Kathmandu any day.'),
    (35, 'GENERIC_SAD', 'I''m trying to see the light, but today I can only see the dark.'),
    (35, 'GENERIC_SAD', 'I''m feeling blue today... come back tomorrow.'),
    (35, 'GREET_OWNER', 'Greetings. Did you bring that kale smoothie I asked for?'),
    (35, 'GREET_OWNER', 'Hello again. Did you read that Zen Mind book I lent you?'),
    (35, 'GREET_OWNER', 'Hello. You''re looking... enlightened today, may I say.'),
    (35, 'HUNGRY', 'I''m hungry, as opposed to starving.'),
    (35, 'HUNGRY', 'I haven''t eaten all day. Help.'),
    (35, 'HUNGRY', 'Hey, I could really do with some food, comrade.'),
    (35, 'HUNGRY', 'In my opinon, vegetarians should reconsider eating cheese or drinking milk.'),
    (35, 'LEVEL_UP', '*DING* I''m on the up.'),
    (35, 'LEVEL_UP', '*DING* Another level, done.'),
    (35, 'LEVEL_UP', '*DING* I just advanced another level. But what does that MEAN?'),
    (35, 'LEVEL_UP', '*DING* Another level. Are you proud?'),
    (35, 'MUTED', 'I could honestly not care less if I''m muted. I''ll be right here listening to my jungle tape packs.'),
    (35, 'PLAYFUL', 'You should really check out this Artificial Intelligence podcast I''m listening to.'),
    (35, 'PLAYFUL', 'Did you know the observable universe has more than 100 BILLION galaxies?'),
    (35, 'PLAYING', 'Marx actually made a lot of sense. Sometimes he made zero sense.'),
    (35, 'PLAYING', 'Do Androids Dream of Electric Sheep?'),
    (35, 'SLEEPING', '*Dreams of electric sheep*'),
    (35, 'SLEEPING', '*zzZZzz..zz..zzZZzz*'),
    (35, 'SLEEPING', '*Rolls over and has a mouthful of grass mid-sleep*'),
    (35, 'THIRSTY', 'You can lead a cow to water, and it''ll ALWAYS drink.'),
    (35, 'THIRSTY', '97% of the world''s water is salty or otherwise undrinkable. By the way, I''m thirsty.'),
    (35, 'THIRSTY', 'Would you do me a COLOSSAL favour and get me a drink?'),
    (35, 'TIRED', 'That existentialism debate has absolutely destroyed me. Good night.'),
    (35, 'TIRED', 'Time for me to shut down for the day, dear friend.'),
    (35, 'TIRED', 'Time to sleep - one of my favourite phrases.'),
    (35, 'UNKNOWN_COMMAND', 'So. You''re going to need to explain that a bit better...'),
    (35, 'UNKNOWN_COMMAND', 'Sorry, I don''t understand. Repeat.');
