-- Pet command names, lifted verbatim from the client's own text bundle
-- (external_flash_texts.txt, keys pet.command.<id>).
--
-- AS3 has no "issue pet command" packet: PetCommandTool posts the command as ordinary chat,
-- "<pet name> <localised command>", and the server is expected to recognise it. These are the
-- exact strings the client shows on the training buttons, so they are what a player types.

INSERT INTO pet_command_names (command, name) VALUES
(0, 'Free'),
(1, 'Sit'),
(2, 'Down'),
(3, 'Here'),
(4, 'Beg'),
(5, 'Play dead'),
(6, 'Stay'),
(7, 'Follow'),
(8, 'Stand'),
(9, 'Jump'),
(10, 'Speak'),
(11, 'Play'),
(12, 'Silent'),
(13, 'Nest'),
(14, 'Drink'),
(15, 'Follow left'),
(16, 'Follow right'),
(17, 'Play football'),
(18, 'Come here'),
(19, 'Bounce'),
(20, 'Flat'),
(21, 'Dance'),
(22, 'Spin'),
(23, 'Switch TV'),
(24, 'Move forward'),
(25, 'Turn left'),
(26, 'Turn right'),
(27, 'Relax'),
(28, 'Croak'),
(29, 'Dip'),
(30, 'Wave'),
(31, 'Mambo!'),
(32, 'High jump'),
(33, 'Chicken dance'),
(34, 'Triple jump'),
(35, 'Spread wings'),
(36, 'Breathe fire'),
(37, 'Hang'),
(38, 'Torch'),
(40, 'Swing'),
(41, 'Roll'),
(42, 'Ring of fire'),
(43, 'Eat'),
(44, 'Wag Tail'),
(45, 'Count'),
(46, 'Breed');
