using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Vortex.Specs.Yaml;

namespace Vortex.Specs.Completeness;

/// <summary>One generated file, path relative to <c>docs/completeness/generated</c>.</summary>
public sealed record GeneratedFile(string RelativePath, string Content);

/// <summary>
/// Renders the report into the generated tree.
/// </summary>
/// <remarks>
/// Pure up to <see cref="Write"/> on purpose, and free of timestamps and commit ids. Two runs over an
/// unchanged checkout have to produce byte-identical files or the tree churns in every diff and
/// nobody reads it — which also means a matrix that did change says something real happened.
/// </remarks>
public static class CompletenessWriter
{
    private const string Preamble =
        "Generated by `habbo-spec completeness --write`. Never hand-edited: everything here is\n"
        + "reproduced from the target client and the current code on the next run.\n";

    public static IReadOnlyList<GeneratedFile> Render(CompletenessReport report)
    {
        List<GeneratedFile> files =
        [
            new("SUMMARY.md", Summary(report)),
            new("FEATURE-MATRIX.md", Matrix(report)),
            new("matrix.yaml", MatrixYaml(report)),
        ];

        files.AddRange(
            report.Domains.Select(d => new GeneratedFile(
                $"domains/{FileName(d.Domain)}.md",
                Domain(report, d)
            ))
        );

        return [.. files.OrderBy(f => f.RelativePath, StringComparer.Ordinal)];
    }

    /// <summary>Writes the tree, removing stale domain pages so the output is the whole truth.</summary>
    public static IReadOnlyList<string> Write(string generatedRoot, CompletenessReport report)
    {
        IReadOnlyList<GeneratedFile> files = Render(report);
        string domains = Path.Combine(generatedRoot, "domains");

        Directory.CreateDirectory(domains);

        HashSet<string> keep =
        [
            .. files.Select(f => Path.GetFullPath(Path.Combine(generatedRoot, f.RelativePath))),
        ];

        foreach (string stale in Directory.EnumerateFiles(domains, "*.md"))
        {
            if (!keep.Contains(Path.GetFullPath(stale)))
            {
                File.Delete(stale);
            }
        }

        foreach (GeneratedFile file in files)
        {
            string path = Path.Combine(generatedRoot, file.RelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, file.Content);
        }

        return [.. files.Select(f => f.RelativePath)];
    }

    private static string Summary(CompletenessReport report)
    {
        StringBuilder text = new();

        text.Append("# Vortex functional completeness\n\n").Append(Preamble).Append('\n');

        if (!report.HasTargetClient)
        {
            text.Append(
                "**No same-revision official client was found.** There is no obligation surface to\n"
                    + "measure against, so this report carries no counts and no percentage. An empty\n"
                    + "denominator is not completeness.\n\n"
            );
            AppendProblems(text, report);
            return text.ToString();
        }

        text.Append("## Target surface\n\n");
        AppendTable(
            text,
            ["measure", "value"],
            [
                ["target client", report.TargetRevision!],
                ["source", report.TargetOrigin!],
                ["incoming obligations", Number(report.Obligations.Count)],
                ["unresolved surface", Number(report.UnresolvedSurface.Count)],
            ]
        );

        text.Append("\n## Coverage\n\n");
        AppendTable(
            text,
            ["axis", "value"],
            [
                ["protocol mapping", report.Share(report.Mapped)],
                ["implementation", report.Share(report.Implemented)],
                ["verified complete", report.Share(report.Count(ObligationStatus.Complete))],
            ]
        );

        text.Append(
            "\n`protocol mapping` counts obligations Vortex can receive at all. `implementation`\n"
                + "counts a meaningful path behind them. `verified complete` counts the ones somebody\n"
                + "checked against the protocol and wrote the evidence down.\n"
        );

        text.Append("\n## Status\n\n");
        AppendTable(
            text,
            ["status", "count"],
            [
                .. ObligationStatusNames.Scored.Select(s =>
                    new[] { s.Wire(), Number(report.Count(s)) }
                ),
            ]
        );

        text.Append("\n## Domains\n\n");
        AppendTable(
            text,
            ["domain", "obligations", .. ObligationStatusNames.Scored.Select(s => s.Wire())],
            [
                .. report.Domains.Select(d =>
                    new[] { d.Domain, Number(d.Obligations.Count) }
                        .Concat(ObligationStatusNames.Scored.Select(s => Number(d.Count(s))))
                        .ToArray()
                ),
            ]
        );

        AppendProblems(text, report);

        return text.ToString();
    }

    private static string Matrix(CompletenessReport report)
    {
        StringBuilder text = new();

        text.Append("# Feature matrix\n\n").Append(Preamble).Append('\n');

        if (!report.HasTargetClient)
        {
            text.Append("No same-revision official client; no obligations to list.\n");
            return text.ToString();
        }

        text.Append("## Obligations\n\n");
        AppendTable(
            text,
            ["status", "domain", "obligation", "header", "handler", "feature", "why"],
            [
                .. report.Obligations.Select(o =>
                    new[]
                    {
                        o.Status.Wire(),
                        o.Domain,
                        o.Name,
                        o.HeaderId is int id ? Number(id) : "-",
                        o.VortexHandler ?? "-",
                        o.FeatureId ?? "-",
                        o.Reason,
                    }
                ),
            ]
        );

        if (report.UnresolvedSurface.Count == 0)
        {
            return text.ToString();
        }

        text.Append(
            "\n## Unresolved surface\n\n"
                + "Client classes that read the wire but that no header id binds. Outside the\n"
                + "denominator, and listed because a surface nobody can classify is not a surface\n"
                + "nobody has to implement.\n\n"
        );
        AppendTable(
            text,
            ["domain", "client class", "reads as"],
            [.. report.UnresolvedSurface.Select(o => new[] { o.Domain, o.ClientClass, o.Name })]
        );

        return text.ToString();
    }

    private static string Domain(CompletenessReport report, DomainSummary domain)
    {
        StringBuilder text = new();

        text.Append("# ").Append(domain.Domain).Append("\n\n").Append(Preamble).Append('\n');
        text.Append("Target client: `").Append(report.TargetRevision).Append("`\n\n");

        AppendTable(
            text,
            ["status", "count"],
            [
                ["obligations", Number(domain.Obligations.Count)],
                .. ObligationStatusNames.Scored.Select(s =>
                    new[] { s.Wire(), Number(domain.Count(s)) }
                ),
            ]
        );

        foreach (ObligationStatus status in ObligationStatusNames.Scored)
        {
            List<Obligation> entries = [.. domain.Obligations.Where(o => o.Status == status)];

            if (entries.Count == 0)
            {
                continue;
            }

            text.Append("\n## ").Append(status.Wire()).Append("\n\n");

            foreach (Obligation entry in entries)
            {
                text.Append("- `")
                    .Append(entry.Name)
                    .Append('`')
                    .Append(entry.HeaderId is int id ? $" ({Number(id)})" : string.Empty)
                    .Append(" — ")
                    .Append(OneLine(entry.Reason))
                    .Append('\n');
            }
        }

        return text.ToString();
    }

    private static string MatrixYaml(CompletenessReport report)
    {
        YamlMapping counts = YamlNode.Mapping();

        foreach (ObligationStatus status in ObligationStatusNames.Scored)
        {
            counts.Set(status.Wire(), report.Count(status));
        }

        YamlMapping root = YamlNode
            .Mapping()
            .Set("version", 1)
            .Set("target_revision", report.TargetRevision)
            .Set("target_origin", report.TargetOrigin)
            .Set("obligation_count", report.Obligations.Count)
            .Set("mapped", report.Mapped)
            .Set("unresolved_surface_count", report.UnresolvedSurface.Count)
            .Set("counts", counts)
            .Set("obligations", YamlNode.Sequence(report.Obligations.Select(Entry)))
            .Set("unresolved_surface", YamlNode.Sequence(report.UnresolvedSurface.Select(Entry)))
            .Set("problems", YamlNode.Sequence(report.Problems.Select(p => YamlNode.Scalar(p))));

        return YamlWriter.Write(
            root,
            "Generated by `habbo-spec completeness --write`. Never hand-edited.\n"
                + "The denominator is the same-revision official client and nothing else."
        );
    }

    private static YamlMapping Entry(Obligation obligation)
    {
        YamlMapping node = YamlNode
            .Mapping()
            .Set("id", obligation.Id)
            .Set("name", obligation.Name)
            .Set("domain", obligation.Domain)
            .Set("status", obligation.Status.Wire())
            .Set("client_class", obligation.ClientClass);

        if (obligation.HeaderId is int header)
        {
            node.Set("header_id", header);
        }

        node.Set("mapped_in_vortex", obligation.MappedInVortex);
        node.SetIfPresent("vortex_handler", obligation.VortexHandler);
        node.SetIfPresent("feature", obligation.FeatureId);
        node.Set("reason", OneLine(obligation.Reason));
        node.SetIfPresent("decision", obligation.DecisionId);
        node.SetIfPresent("verified_at_commit", obligation.VerifiedAtCommit);
        node.SetIfAny(
            "conflicts",
            YamlNode.Sequence(obligation.ConflictIds.Select(c => YamlNode.Scalar(c)))
        );
        node.SetIfAny(
            "unknowns",
            YamlNode.Sequence(obligation.UnknownIds.Select(u => YamlNode.Scalar(u)))
        );

        return node;
    }

    private static void AppendProblems(StringBuilder text, CompletenessReport report)
    {
        text.Append("\n## Problems\n\n");

        if (report.Problems.Count == 0)
        {
            text.Append("None.\n");
            return;
        }

        foreach (string problem in report.Problems)
        {
            text.Append("- ").Append(OneLine(problem)).Append('\n');
        }
    }

    private static void AppendTable(
        StringBuilder text,
        IReadOnlyList<string> headers,
        IReadOnlyList<string[]> rows
    )
    {
        text.Append("| ").Append(string.Join(" | ", headers)).Append(" |\n");
        text.Append("|").Append(string.Concat(headers.Select(_ => "---|"))).Append('\n');

        foreach (string[] row in rows)
        {
            text.Append("| ").Append(string.Join(" | ", row.Select(Cell))).Append(" |\n");
        }
    }

    private static string Cell(string value) =>
        OneLine(value).Replace("|", "\\|", StringComparison.Ordinal);

    private static string OneLine(string value) =>
        value
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace('\n', ' ')
            .Replace('\r', ' ')
            .Trim();

    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>A domain name reduced to something safe on every filesystem this runs on.</summary>
    private static string FileName(string domain)
    {
        StringBuilder name = new(domain.Length);

        foreach (char c in domain)
        {
            name.Append(
                char.IsAsciiLetterOrDigit(c) || c is '-' or '_' ? char.ToLowerInvariant(c) : '-'
            );
        }

        return name.ToString().Trim('-') is { Length: > 0 } slug ? slug : "unsorted";
    }
}
