using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vortex.Database.Entities.Furniture;

/// <summary>
/// One avatar figure set a clothing furni hands over when it is redeemed.
/// </summary>
/// <remarks>
/// <para>
/// A furni grants one row per set, because an outfit is usually several: a hat, a top and a pair of
/// boots redeemed together. The pair is unique, so re-running the seed cannot double a grant.
/// </para>
/// <para>
/// Reference data, not admin data. The values come from the shipped furnidata — each clothing
/// furni's <c>customparams</c> is the list of set ids, and the client reads the same field to draw
/// the preview before the server is involved. Regenerated by
/// <c>tools/catalog_converter/scan_purchasable_clothing.py</c>; typing it by hand would be 3 687
/// rows of a mapping the hotel already ships.
/// </para>
/// </remarks>
[Table("furniture_purchasable_clothing")]
[Index(
    nameof(FurnitureDefinitionEntityId),
    nameof(FigureSetId),
    IsUnique = true,
    Name = "IX_furniture_purchasable_clothing_definition_set"
)]
public class FurniturePurchasableClothingEntity : VortexEntity
{
    [Column("furniture_definition_id")]
    public required int FurnitureDefinitionEntityId { get; set; }

    /// <summary>The figure set id, as figuredata numbers it and as the avatar figure string carries
    /// it.</summary>
    [Column("figure_set_id")]
    public required int FigureSetId { get; set; }

    [ForeignKey(nameof(FurnitureDefinitionEntityId))]
    public FurnitureDefinitionEntity? FurnitureDefinitionEntity { get; set; }
}
